// Generated by the Supabase MCP generate_typescript_types tool against the
// production schema on 2026-08-11 (AUD#22). Regenerate after any migration:
// the db-replay CI gate doesn't check this file — drift shows up as tsc
// errors at the call sites that rely on it, not here.
//
// Do not hand-edit.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.1"
  }
  public: {
    Tables: {
      activity_events: {
        Row: {
          actor_id: string
          created_at: string | null
          event_type: string
          game_id: string | null
          id: string
          match_id: string | null
          metadata: Json | null
        }
        Insert: {
          actor_id: string
          created_at?: string | null
          event_type: string
          game_id?: string | null
          id?: string
          match_id?: string | null
          metadata?: Json | null
        }
        Update: {
          actor_id?: string
          created_at?: string | null
          event_type?: string
          game_id?: string | null
          id?: string
          match_id?: string | null
          metadata?: Json | null
        }
        Relationships: [
          {
            foreignKeyName: "activity_events_league_id_fkey"
            columns: ["game_id"]
            isOneToOne: false
            referencedRelation: "games"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "activity_events_league_id_fkey"
            columns: ["game_id"]
            isOneToOne: false
            referencedRelation: "my_games_with_period"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "activity_events_match_id_fkey"
            columns: ["match_id"]
            isOneToOne: false
            referencedRelation: "matches"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "activity_events_match_id_fkey"
            columns: ["match_id"]
            isOneToOne: false
            referencedRelation: "my_upcoming_matches"
            referencedColumns: ["id"]
          },
        ]
      }
      course_holes: {
        Row: {
          course_id: string
          dist_yellow_m: number | null
          hcp_index: number | null
          hole_number: number
          id: string
          par: number
          tee_note: string | null
        }
        Insert: {
          course_id: string
          dist_yellow_m?: number | null
          hcp_index?: number | null
          hole_number: number
          id?: string
          par: number
          tee_note?: string | null
        }
        Update: {
          course_id?: string
          dist_yellow_m?: number | null
          hcp_index?: number | null
          hole_number?: number
          id?: string
          par?: number
          tee_note?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "course_holes_course_id_fkey"
            columns: ["course_id"]
            isOneToOne: false
            referencedRelation: "courses"
            referencedColumns: ["id"]
          },
        ]
      }
      courses: {
        Row: {
          access: string | null
          city: string | null
          course_type: string | null
          created_at: string
          department: string | null
          dept_no: string | null
          dist_red: number | null
          dist_white: number | null
          dist_yellow: number | null
          holes: number | null
          id: string
          name: string
          par: number | null
          postcode: string | null
          slug: string | null
        }
        Insert: {
          access?: string | null
          city?: string | null
          course_type?: string | null
          created_at?: string
          department?: string | null
          dept_no?: string | null
          dist_red?: number | null
          dist_white?: number | null
          dist_yellow?: number | null
          holes?: number | null
          id?: string
          name: string
          par?: number | null
          postcode?: string | null
          slug?: string | null
        }
        Update: {
          access?: string | null
          city?: string | null
          course_type?: string | null
          created_at?: string
          department?: string | null
          dept_no?: string | null
          dist_red?: number | null
          dist_white?: number | null
          dist_yellow?: number | null
          holes?: number | null
          id?: string
          name?: string
          par?: number | null
          postcode?: string | null
          slug?: string | null
        }
        Relationships: []
      }
      game_members: {
        Row: {
          game_id: string
          id: string
          joined_at: string | null
          role: string
          team: number | null
          user_id: string
        }
        Insert: {
          game_id: string
          id?: string
          joined_at?: string | null
          role?: string
          team?: number | null
          user_id: string
        }
        Update: {
          game_id?: string
          id?: string
          joined_at?: string | null
          role?: string
          team?: number | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "league_members_league_id_fkey"
            columns: ["game_id"]
            isOneToOne: false
            referencedRelation: "games"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "league_members_league_id_fkey"
            columns: ["game_id"]
            isOneToOne: false
            referencedRelation: "my_games_with_period"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "league_members_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      game_periods: {
        Row: {
          created_at: string | null
          end_date: string
          game_id: string
          id: string
          name: string
          start_date: string
          status: string
          week_number: number
        }
        Insert: {
          created_at?: string | null
          end_date: string
          game_id: string
          id?: string
          name: string
          start_date: string
          status?: string
          week_number: number
        }
        Update: {
          created_at?: string | null
          end_date?: string
          game_id?: string
          id?: string
          name?: string
          start_date?: string
          status?: string
          week_number?: number
        }
        Relationships: [
          {
            foreignKeyName: "league_periods_league_id_fkey"
            columns: ["game_id"]
            isOneToOne: false
            referencedRelation: "games"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "league_periods_league_id_fkey"
            columns: ["game_id"]
            isOneToOne: false
            referencedRelation: "my_games_with_period"
            referencedColumns: ["id"]
          },
        ]
      }
      games: {
        Row: {
          admin_id: string
          course_id: string | null
          course_name: string
          created_at: string | null
          end_date: string | null
          format: string
          game_type: string
          id: string
          invite_code: string
          is_practice: boolean
          max_players: number
          name: string
          scoring_basis: string
          scoring_cards_count: number | null
          start_date: string | null
          status: string
          team_mode: boolean
          team1_name: string | null
          team2_name: string | null
          total_cards_count: number | null
        }
        Insert: {
          admin_id: string
          course_id?: string | null
          course_name: string
          created_at?: string | null
          end_date?: string | null
          format?: string
          game_type?: string
          id?: string
          invite_code?: string
          is_practice?: boolean
          max_players: number
          name: string
          scoring_basis?: string
          scoring_cards_count?: number | null
          start_date?: string | null
          status?: string
          team_mode?: boolean
          team1_name?: string | null
          team2_name?: string | null
          total_cards_count?: number | null
        }
        Update: {
          admin_id?: string
          course_id?: string | null
          course_name?: string
          created_at?: string | null
          end_date?: string | null
          format?: string
          game_type?: string
          id?: string
          invite_code?: string
          is_practice?: boolean
          max_players?: number
          name?: string
          scoring_basis?: string
          scoring_cards_count?: number | null
          start_date?: string | null
          status?: string
          team_mode?: boolean
          team1_name?: string | null
          team2_name?: string | null
          total_cards_count?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "games_course_id_fkey"
            columns: ["course_id"]
            isOneToOne: false
            referencedRelation: "courses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "leagues_admin_id_fkey"
            columns: ["admin_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      join_requests: {
        Row: {
          admin_id: string
          created_at: string | null
          id: string
          requester_id: string
          resolved_at: string | null
          resolved_by: string | null
          status: string
          target_id: string
          target_type: string
        }
        Insert: {
          admin_id: string
          created_at?: string | null
          id?: string
          requester_id: string
          resolved_at?: string | null
          resolved_by?: string | null
          status?: string
          target_id: string
          target_type: string
        }
        Update: {
          admin_id?: string
          created_at?: string | null
          id?: string
          requester_id?: string
          resolved_at?: string | null
          resolved_by?: string | null
          status?: string
          target_id?: string
          target_type?: string
        }
        Relationships: []
      }
      leads: {
        Row: {
          created_at: string
          email: string
          id: string
          name: string
          notes: string | null
          source: string | null
          source_image: string | null
          source_page: string | null
          status: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          email: string
          id?: string
          name: string
          notes?: string | null
          source?: string | null
          source_image?: string | null
          source_page?: string | null
          status?: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          email?: string
          id?: string
          name?: string
          notes?: string | null
          source?: string | null
          source_image?: string | null
          source_page?: string | null
          status?: string
          updated_at?: string
        }
        Relationships: []
      }
      match_approvals: {
        Row: {
          created_at: string | null
          id: string
          match_id: string
          user_id: string
        }
        Insert: {
          created_at?: string | null
          id?: string
          match_id: string
          user_id: string
        }
        Update: {
          created_at?: string | null
          id?: string
          match_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "match_approvals_match_id_fkey"
            columns: ["match_id"]
            isOneToOne: false
            referencedRelation: "matches"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "match_approvals_match_id_fkey"
            columns: ["match_id"]
            isOneToOne: false
            referencedRelation: "my_upcoming_matches"
            referencedColumns: ["id"]
          },
        ]
      }
      match_players: {
        Row: {
          approved_at: string | null
          id: string
          joined_at: string | null
          match_id: string
          playing_handicap: number | null
          team: number | null
          user_id: string
        }
        Insert: {
          approved_at?: string | null
          id?: string
          joined_at?: string | null
          match_id: string
          playing_handicap?: number | null
          team?: number | null
          user_id: string
        }
        Update: {
          approved_at?: string | null
          id?: string
          joined_at?: string | null
          match_id?: string
          playing_handicap?: number | null
          team?: number | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "match_players_match_id_fkey"
            columns: ["match_id"]
            isOneToOne: false
            referencedRelation: "matches"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "match_players_match_id_fkey"
            columns: ["match_id"]
            isOneToOne: false
            referencedRelation: "my_upcoming_matches"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "match_players_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      matches: {
        Row: {
          course_id: string | null
          course_name: string
          created_at: string | null
          created_by: string
          game_id: string | null
          id: string
          last_edit_at: string | null
          live_share_token: string | null
          match_date: string
          match_time: string | null
          period_id: string | null
          status: string
        }
        Insert: {
          course_id?: string | null
          course_name: string
          created_at?: string | null
          created_by: string
          game_id?: string | null
          id?: string
          last_edit_at?: string | null
          live_share_token?: string | null
          match_date: string
          match_time?: string | null
          period_id?: string | null
          status?: string
        }
        Update: {
          course_id?: string | null
          course_name?: string
          created_at?: string | null
          created_by?: string
          game_id?: string | null
          id?: string
          last_edit_at?: string | null
          live_share_token?: string | null
          match_date?: string
          match_time?: string | null
          period_id?: string | null
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "matches_course_id_fkey"
            columns: ["course_id"]
            isOneToOne: false
            referencedRelation: "courses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "matches_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "matches_league_id_fkey"
            columns: ["game_id"]
            isOneToOne: false
            referencedRelation: "games"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "matches_league_id_fkey"
            columns: ["game_id"]
            isOneToOne: false
            referencedRelation: "my_games_with_period"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "matches_period_id_fkey"
            columns: ["period_id"]
            isOneToOne: false
            referencedRelation: "game_periods"
            referencedColumns: ["id"]
          },
        ]
      }
      newsletter_subscribers: {
        Row: {
          email: string
          id: string
          source: string | null
          subscribed_at: string | null
        }
        Insert: {
          email: string
          id?: string
          source?: string | null
          subscribed_at?: string | null
        }
        Update: {
          email?: string
          id?: string
          source?: string | null
          subscribed_at?: string | null
        }
        Relationships: []
      }
      notifications: {
        Row: {
          body: string | null
          created_at: string | null
          data: Json | null
          id: string
          read_at: string | null
          title: string
          type: string
          user_id: string
        }
        Insert: {
          body?: string | null
          created_at?: string | null
          data?: Json | null
          id?: string
          read_at?: string | null
          title: string
          type: string
          user_id: string
        }
        Update: {
          body?: string | null
          created_at?: string | null
          data?: Json | null
          id?: string
          read_at?: string | null
          title?: string
          type?: string
          user_id?: string
        }
        Relationships: []
      }
      player_ratings: {
        Row: {
          matches_rated: number
          rating: number
          updated_at: string
          user_id: string
        }
        Insert: {
          matches_rated?: number
          rating?: number
          updated_at?: string
          user_id: string
        }
        Update: {
          matches_rated?: number
          rating?: number
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "player_ratings_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          avatar_url: string | null
          club: string | null
          created_at: string | null
          email: string
          first_name: string
          handicap: number | null
          id: string
          last_name: string | null
          town: string | null
          username: string | null
        }
        Insert: {
          avatar_url?: string | null
          club?: string | null
          created_at?: string | null
          email: string
          first_name: string
          handicap?: number | null
          id: string
          last_name?: string | null
          town?: string | null
          username?: string | null
        }
        Update: {
          avatar_url?: string | null
          club?: string | null
          created_at?: string | null
          email?: string
          first_name?: string
          handicap?: number | null
          id?: string
          last_name?: string | null
          town?: string | null
          username?: string | null
        }
        Relationships: []
      }
      push_subscriptions: {
        Row: {
          auth: string
          created_at: string | null
          endpoint: string
          id: string
          p256dh: string
          user_id: string
        }
        Insert: {
          auth: string
          created_at?: string | null
          endpoint: string
          id?: string
          p256dh: string
          user_id: string
        }
        Update: {
          auth?: string
          created_at?: string | null
          endpoint?: string
          id?: string
          p256dh?: string
          user_id?: string
        }
        Relationships: []
      }
      rating_history: {
        Row: {
          created_at: string
          id: string
          match_id: string
          rating_after: number
          rating_before: number
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          match_id: string
          rating_after: number
          rating_before: number
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          match_id?: string
          rating_after?: number
          rating_before?: number
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "rating_history_match_id_fkey"
            columns: ["match_id"]
            isOneToOne: false
            referencedRelation: "matches"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "rating_history_match_id_fkey"
            columns: ["match_id"]
            isOneToOne: false
            referencedRelation: "my_upcoming_matches"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "rating_history_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      score_approvals: {
        Row: {
          approved_by: string
          created_at: string | null
          id: string
          score_id: string
        }
        Insert: {
          approved_by: string
          created_at?: string | null
          id?: string
          score_id: string
        }
        Update: {
          approved_by?: string
          created_at?: string | null
          id?: string
          score_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "score_approvals_approved_by_fkey"
            columns: ["approved_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "score_approvals_score_id_fkey"
            columns: ["score_id"]
            isOneToOne: false
            referencedRelation: "scores"
            referencedColumns: ["id"]
          },
        ]
      }
      score_holes: {
        Row: {
          hole_number: number
          id: string
          score_id: string
          strokes: number
        }
        Insert: {
          hole_number: number
          id?: string
          score_id: string
          strokes: number
        }
        Update: {
          hole_number?: number
          id?: string
          score_id?: string
          strokes?: number
        }
        Relationships: [
          {
            foreignKeyName: "score_holes_score_id_fkey"
            columns: ["score_id"]
            isOneToOne: false
            referencedRelation: "scores"
            referencedColumns: ["id"]
          },
        ]
      }
      score_revisions: {
        Row: {
          changed_at: string
          changed_by: string | null
          id: string
          match_id: string
          new_holes: number | null
          new_score: number | null
          old_holes: number | null
          old_score: number | null
          user_id: string
        }
        Insert: {
          changed_at?: string
          changed_by?: string | null
          id?: string
          match_id: string
          new_holes?: number | null
          new_score?: number | null
          old_holes?: number | null
          old_score?: number | null
          user_id: string
        }
        Update: {
          changed_at?: string
          changed_by?: string | null
          id?: string
          match_id?: string
          new_holes?: number | null
          new_score?: number | null
          old_holes?: number | null
          old_score?: number | null
          user_id?: string
        }
        Relationships: []
      }
      scores: {
        Row: {
          approved_at: string | null
          approved_by: string | null
          created_at: string | null
          holes: number
          id: string
          match_id: string
          score: number
          status: string | null
          submitted_by: string | null
          user_id: string
        }
        Insert: {
          approved_at?: string | null
          approved_by?: string | null
          created_at?: string | null
          holes?: number
          id?: string
          match_id: string
          score: number
          status?: string | null
          submitted_by?: string | null
          user_id: string
        }
        Update: {
          approved_at?: string | null
          approved_by?: string | null
          created_at?: string | null
          holes?: number
          id?: string
          match_id?: string
          score?: number
          status?: string | null
          submitted_by?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "scores_match_id_fkey"
            columns: ["match_id"]
            isOneToOne: false
            referencedRelation: "matches"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "scores_match_id_fkey"
            columns: ["match_id"]
            isOneToOne: false
            referencedRelation: "my_upcoming_matches"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "scores_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      user_notification_preferences: {
        Row: {
          notification_type: string
          push_enabled: boolean
          updated_at: string | null
          user_id: string
        }
        Insert: {
          notification_type: string
          push_enabled?: boolean
          updated_at?: string | null
          user_id: string
        }
        Update: {
          notification_type?: string
          push_enabled?: boolean
          updated_at?: string | null
          user_id?: string
        }
        Relationships: []
      }
    }
    Views: {
      my_games_with_period: {
        Row: {
          admin_id: string | null
          course_name: string | null
          created_at: string | null
          current_period_name: string | null
          current_week: number | null
          game_type: string | null
          id: string | null
          invite_code: string | null
          max_players: number | null
          name: string | null
          period_end: string | null
          period_start: string | null
          player_count: number | null
          status: string | null
          total_weeks: number | null
        }
        Relationships: [
          {
            foreignKeyName: "leagues_admin_id_fkey"
            columns: ["admin_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      my_upcoming_matches: {
        Row: {
          course_name: string | null
          created_at: string | null
          created_by: string | null
          game_course: string | null
          game_id: string | null
          game_name: string | null
          id: string | null
          match_date: string | null
          match_time: string | null
          period_id: string | null
          period_name: string | null
          status: string | null
        }
        Relationships: [
          {
            foreignKeyName: "matches_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "matches_league_id_fkey"
            columns: ["game_id"]
            isOneToOne: false
            referencedRelation: "games"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "matches_league_id_fkey"
            columns: ["game_id"]
            isOneToOne: false
            referencedRelation: "my_games_with_period"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "matches_period_id_fkey"
            columns: ["period_id"]
            isOneToOne: false
            referencedRelation: "game_periods"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Functions: {
      advance_game_period: { Args: { p_game_id: string }; Returns: Json }
      allocate_strokes: {
        Args: { p_course_id: string; p_playing_handicap: number }
        Returns: {
          hole_number: number
          strokes_received: number
        }[]
      }
      approve_join_request: { Args: { p_request_id: string }; Returns: Json }
      approve_match_scores: { Args: { p_match_id: string }; Returns: Json }
      approve_score: { Args: { p_score_id: string }; Returns: Json }
      auto_approve_stale_scores: { Args: never; Returns: undefined }
      auto_complete_stale_matches: {
        Args: never
        Returns: {
          completed_match_id: string
        }[]
      }
      backfill_course_ids: { Args: never; Returns: Json }
      backfill_ratings: { Args: never; Returns: Json }
      check_and_finalize_match_scores: {
        Args: { p_match_id: string }
        Returns: undefined
      }
      create_game: {
        Args: {
          p_course_id?: string
          p_course_name: string
          p_end_date?: string
          p_game_type?: string
          p_max_players: number
          p_name: string
          p_scoring_basis?: string
          p_scoring_cards?: number
          p_start_date?: string
          p_team_mode?: boolean
          p_total_cards?: number
        }
        Returns: Json
      }
      create_notification: {
        Args: {
          p_body?: string
          p_data?: Json
          p_title: string
          p_type: string
          p_user_id: string
        }
        Returns: string
      }
      create_practice_match: {
        Args: { p_course_id?: string; p_course_name?: string }
        Returns: Json
      }
      create_scheduled_match: {
        Args: {
          p_course_id?: string
          p_course_name?: string
          p_game_id: string
          p_match_date: string
          p_match_time?: string
          p_player_ids: string[]
        }
        Returns: Json
      }
      disable_live_share: { Args: { p_match_id: string }; Returns: Json }
      enable_live_share: { Args: { p_match_id: string }; Returns: Json }
      finalize_match_scores: { Args: { p_match_id: string }; Returns: Json }
      generate_game_periods: {
        Args: { p_game_id: string; p_start_date?: string }
        Returns: Json
      }
      get_game_activity_feed: {
        Args: { p_game_id: string; p_limit?: number }
        Returns: {
          out_actor_avatar_url: string
          out_actor_id: string
          out_actor_name: string
          out_created_at: string
          out_event_type: string
          out_game_id: string
          out_id: string
          out_match_id: string
          out_metadata: Json
        }[]
      }
      get_game_badges: {
        Args: { p_game_id: string }
        Returns: {
          avatar_url: string
          badge_key: string
          player_name: string
          sub: string
          unit: string
          user_id: string
          value: number
        }[]
      }
      get_game_recap: { Args: { p_game_id: string }; Returns: Json }
      get_head_to_head: {
        Args: { p_user_a: string; p_user_b: string }
        Returns: Json
      }
      get_invite_preview: { Args: { p_code: string }; Returns: Json }
      get_leaderboard: {
        Args: { p_game_id: string }
        Returns: {
          avatar_url: string
          best_score: number
          player_name: string
          position: number
          rounds_counted: number
          rounds_played: number
          total_score: number
          user_id: string
        }[]
      }
      get_live_match: { Args: { p_token: string }; Returns: Json }
      get_match_play_board: {
        Args: { p_game_id: string }
        Returns: {
          holes_won: number
          match_points: number
          matches_played: number
          user_id: string
        }[]
      }
      get_match_scorecard: { Args: { p_match_id: string }; Returns: Json }
      get_my_notification_preferences: {
        Args: never
        Returns: {
          notification_type: string
          push_enabled: boolean
        }[]
      }
      get_or_create_practice_game: { Args: never; Returns: Json }
      get_profile_course_conquests: {
        Args: { p_user_id: string }
        Returns: {
          conquered: number
          courses_played: number
          dept_no: string
        }[]
      }
      get_profile_courses: {
        Args: { p_user_id: string }
        Returns: {
          best_score: number
          course_city: string
          course_id: string
          course_name: string
          course_par: number
          last_played_date: string
          times_played: number
        }[]
      }
      get_profile_records: { Args: { p_user_id: string }; Returns: Json }
      get_profile_score_trend: {
        Args: { p_range?: string; p_user_id: string }
        Returns: Json
      }
      get_ryder_score: { Args: { p_game_id: string }; Returns: Json }
      get_unread_notification_count: { Args: never; Returns: number }
      get_user_course_stats: {
        Args: { p_course_id: string; p_user_id: string }
        Returns: Json
      }
      get_user_honors: {
        Args: { p_user_id: string }
        Returns: {
          badge_key: string
          game_format: string
          game_id: string
          game_name: string
          sub: string
          unit: string
          value: number
        }[]
      }
      is_game_member: {
        Args: { p_game_id: string; p_user_id: string }
        Returns: boolean
      }
      join_game_by_code: { Args: { code: string }; Returns: Json }
      mark_all_notifications_read: { Args: never; Returns: undefined }
      mark_join_request_notifications_read: {
        Args: { p_request_id: string }
        Returns: undefined
      }
      mark_notifications_read: {
        Args: { p_notification_ids: string[] }
        Returns: undefined
      }
      match_play_state: { Args: { p_match_id: string }; Returns: Json }
      rate_match: { Args: { p_match_id: string }; Returns: number }
      reject_join_request: { Args: { p_request_id: string }; Returns: Json }
      request_join_game: { Args: { p_game_id: string }; Returns: Json }
      request_join_match: { Args: { p_match_id: string }; Returns: Json }
      round_basis_score: {
        Args: { p_basis: string; p_score_id: string }
        Returns: number
      }
      search_courses: {
        Args: { p_limit?: number; p_query: string }
        Returns: {
          city: string
          course_type: string
          department: string
          dept_no: string
          holes: number
          id: string
          name: string
          par: number
        }[]
      }
      search_players: {
        Args: { p_limit?: number; p_query: string }
        Returns: {
          avatar_url: string
          club: string
          first_name: string
          handicap: number
          id: string
          last_name: string
          town: string
          username: string
        }[]
      }
      set_member_team: {
        Args: { p_game_id: string; p_team: number; p_user_id: string }
        Returns: Json
      }
      set_notification_preference: {
        Args: { p_enabled: boolean; p_type: string }
        Returns: undefined
      }
      shares_game_with: { Args: { p_other: string }; Returns: boolean }
      should_send_push: {
        Args: { p_type: string; p_user_id: string }
        Returns: boolean
      }
      submit_match_scores: {
        Args: { p_match_id: string; p_scores: Json }
        Returns: Json
      }
      sync_course_aggregates: {
        Args: { p_course_id: string }
        Returns: undefined
      }
      upsert_score_hole: {
        Args: {
          p_hole_number: number
          p_match_id: string
          p_strokes: number
          p_user_id: string
        }
        Returns: Json
      }
      user_can_see_match: {
        Args: { p_match_id: string; p_user_id: string }
        Returns: boolean
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
