"use client"

import { useState, useEffect } from "react"
import Link from "next/link"

interface SharePageProps {
  params: { matchId: string }
}

/**
 * Public round share page. Renders the OG card image (generated by
 * /api/og/round/[matchId]) and exposes three ways to share:
 *   1. Native share sheet (iOS/Android) via navigator.share
 *   2. Copy link to clipboard
 *   3. Download the card PNG
 *
 * The page itself has OG meta tags pointing to the same image, so
 * if you paste the share link into WhatsApp / iMessage / Twitter /
 * Slack the preview already renders the card.
 */
export default function RoundSharePage({ params }: SharePageProps) {
  const matchId = params.matchId
  const [origin, setOrigin] = useState("")
  const [copied, setCopied] = useState(false)
  const [canNativeShare, setCanNativeShare] = useState(false)

  useEffect(() => {
    if (typeof window === "undefined") return
    setOrigin(window.location.origin)
    setCanNativeShare(typeof navigator !== "undefined" && !!navigator.share)
  }, [])

  const shareUrl = origin ? `${origin}/share/round/${matchId}` : ""
  const imageUrl = origin ? `${origin}/api/og/round/${matchId}` : ""

  const handleCopy = async () => {
    if (!shareUrl || typeof navigator === "undefined") return
    try {
      await navigator.clipboard.writeText(shareUrl)
      setCopied(true)
      setTimeout(() => setCopied(false), 1800)
    } catch {
      // ignore
    }
  }

  const handleNativeShare = async () => {
    if (!shareUrl || typeof navigator === "undefined" || !navigator.share) return
    try {
      await navigator.share({
        title: "Mulligan League round",
        text: "Check out this round on Mulligan League:",
        url: shareUrl,
      })
    } catch {
      // User cancelled — ignore
    }
  }

  return (
    <main className="min-h-screen bg-cream px-4 pb-16 pt-6">
      <div className="mx-auto flex w-full max-w-md flex-col gap-5">
        <header className="flex items-center justify-between">
          <Link
            href={`/matches/${matchId}`}
            className="inline-flex items-center gap-1 text-xs font-medium text-primary/60 hover:text-primary"
          >
            <ChevronLeft />
            Back to match
          </Link>
          <h1 className="text-sm font-semibold text-primary">Share round</h1>
          <span className="w-[68px]" />
        </header>

        {/* Card preview */}
        <div className="overflow-hidden rounded-2xl border border-primary/15 bg-white shadow-sm">
          {imageUrl ? (
            // eslint-disable-next-line @next/next/no-img-element
            <img
              src={imageUrl}
              alt="Round card"
              className="block h-auto w-full"
              width={1080}
              height={1080}
            />
          ) : (
            <div className="flex aspect-square items-center justify-center">
              <div className="h-6 w-6 animate-spin rounded-full border-2 border-primary/20 border-t-primary" />
            </div>
          )}
        </div>

        {/* Actions */}
        <div className="flex flex-col gap-2">
          {canNativeShare && (
            <button
              type="button"
              onClick={handleNativeShare}
              className="flex items-center justify-center gap-2 rounded-lg bg-primary px-4 py-3 text-sm font-medium text-cream transition-colors hover:bg-primary/90"
            >
              <ShareIcon />
              Share
            </button>
          )}

          <button
            type="button"
            onClick={handleCopy}
            className="flex items-center justify-center gap-2 rounded-lg border border-primary/20 bg-white px-4 py-3 text-sm font-medium text-primary transition-colors hover:bg-primary/5"
          >
            <LinkIcon />
            {copied ? "Link copied!" : "Copy share link"}
          </button>

          {imageUrl && (
            <a
              href={imageUrl}
              download={`mulligan-round-${matchId}.png`}
              className="flex items-center justify-center gap-2 rounded-lg border border-primary/20 bg-white px-4 py-3 text-sm font-medium text-primary transition-colors hover:bg-primary/5"
            >
              <DownloadIcon />
              Download image
            </a>
          )}
        </div>

        <p className="mt-2 text-center text-[11px] text-primary/40">
          Anyone with the link can see this round card.
        </p>
      </div>
    </main>
  )
}

/* ── Icons ────────────────────────────────────────────── */

function ChevronLeft() {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="14"
      height="14"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
    >
      <polyline points="15 18 9 12 15 6" />
    </svg>
  )
}

function ShareIcon() {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="16"
      height="16"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
    >
      <circle cx="18" cy="5" r="3" />
      <circle cx="6" cy="12" r="3" />
      <circle cx="18" cy="19" r="3" />
      <line x1="8.59" y1="13.51" x2="15.42" y2="17.49" />
      <line x1="15.41" y1="6.51" x2="8.59" y2="10.49" />
    </svg>
  )
}

function LinkIcon() {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="16"
      height="16"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
    >
      <path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71" />
      <path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71" />
    </svg>
  )
}

function DownloadIcon() {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="16"
      height="16"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
    >
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="7 10 12 15 17 10" />
      <line x1="12" y1="15" x2="12" y2="3" />
    </svg>
  )
}
