-- ============================================================================
-- Seed per-hole scorecards (course_holes) for Île-de-France courses
-- ============================================================================
-- GENERATED by scripts/seed_course_holes.py from Golfs_Ile_de_France.xlsx
-- (97 per-course sheets; see scripts/course_holes_mapping.md for the
-- sheet→course mapping and the sheets rejected as contradictory/unmatched).
-- Courses are addressed by the seed's own idempotency key
-- (lower(name), lower(city)) because course UUIDs differ between CI replays
-- and prod. Safe to re-run: ON CONFLICT (course_id, hole_number) DO UPDATE.
-- ============================================================================

-- Course-row fixes: repairs where the internally-consistent hole card
-- contradicts the résumé-sourced row, plus NULL backfills (par/holes/
-- dist_yellow) so every seeded course carries displayable values.
-- 9-hole convention: par/distance stored as two-loop (18-hole) totals.

UPDATE public.courses SET par = 71 WHERE lower(name) = lower('Crécy Golf - Parcours Vignoly') AND lower(coalesce(city, '')) = lower('Crécy-la-Chapelle');
UPDATE public.courses SET dist_yellow = 5593, holes = 18, par = 72 WHERE lower(name) = lower('Golf Paris Val d''Europe (Disneyland)') AND lower(coalesce(city, '')) = lower('Magny-le-Hongre');
UPDATE public.courses SET par = 72 WHERE lower(name) = lower('Golf de Bussy-Guermantes - La Gondoire') AND lower(coalesce(city, '')) = lower('Bussy-Saint-Georges');
UPDATE public.courses SET dist_yellow = 5529, par = 72 WHERE lower(name) = lower('Golf de Bussy-Guermantes - La Brèche') AND lower(coalesce(city, '')) = lower('Bussy-Saint-Georges');
UPDATE public.courses SET par = 71 WHERE lower(name) = lower('Golf de Meaux-Boutigny') AND lower(coalesce(city, '')) = lower('Boutigny');
UPDATE public.courses SET dist_yellow = 5542, par = 72 WHERE lower(name) = lower('Golf de Montereau la Forteresse') AND lower(coalesce(city, '')) = lower('Thoury-Férottes');
UPDATE public.courses SET dist_yellow = 5469, par = 71 WHERE lower(name) = lower('Golf de Réveillon - Parcours 18T') AND lower(coalesce(city, '')) = lower('Lésigny');
UPDATE public.courses SET dist_yellow = 5376, par = 72 WHERE lower(name) = lower('Golf de Torcy') AND lower(coalesce(city, '')) = lower('Torcy');
UPDATE public.courses SET dist_yellow = 5411, par = 71 WHERE lower(name) = lower('Exclusiv Golf de Rochefort') AND lower(coalesce(city, '')) = lower('Rochefort-en-Yvelines');
UPDATE public.courses SET dist_yellow = 5483, holes = 18, par = 72 WHERE lower(name) = lower('Golf Blue Green de Guerville') AND lower(coalesce(city, '')) = lower('Guerville');
UPDATE public.courses SET dist_yellow = 5034, par = 70 WHERE lower(name) = lower('Golf Blue Green de Villennes') AND lower(coalesce(city, '')) = lower('Villennes-sur-Seine');
UPDATE public.courses SET dist_yellow = 5550, par = 73 WHERE lower(name) = lower('Golf Country Club de Fourqueux - Blanc/Bleu') AND lower(coalesce(city, '')) = lower('Fourqueux');
UPDATE public.courses SET dist_yellow = 5741, par = 72 WHERE lower(name) = lower('Golf de Saint-Quentin-en-Yvelines - Bleu') AND lower(coalesce(city, '')) = lower('Trappes');
UPDATE public.courses SET dist_yellow = 5456, par = 72 WHERE lower(name) = lower('Golf de Saint-Quentin-en-Yvelines - Rouge') AND lower(coalesce(city, '')) = lower('Trappes');
UPDATE public.courses SET dist_yellow = 5719, par = 72 WHERE lower(name) = lower('Golf de Villacoublay (Région Aérienne)') AND lower(coalesce(city, '')) = lower('Vélizy-Villacoublay');
UPDATE public.courses SET dist_yellow = 5901, par = 72 WHERE lower(name) = lower('Golf de la Boulie - La Forêt') AND lower(coalesce(city, '')) = lower('Versailles');
UPDATE public.courses SET dist_yellow = 5450, par = 72 WHERE lower(name) = lower('Golf du Tremblay-sur-Mauldre - Château') AND lower(coalesce(city, '')) = lower('Le Tremblay-sur-Mauldre');
UPDATE public.courses SET dist_yellow = 1112, par = 54 WHERE lower(name) = lower('Golf du Tremblay-sur-Mauldre - Le Parc') AND lower(coalesce(city, '')) = lower('Le Tremblay-sur-Mauldre');
UPDATE public.courses SET par = 56 WHERE lower(name) = lower('Île Fleurie Golf Club') AND lower(coalesce(city, '')) = lower('Chatou');
UPDATE public.courses SET dist_yellow = 5670, par = 72 WHERE lower(name) = lower('Golf de la Boulie - La Vallée') AND lower(coalesce(city, '')) = lower('Versailles');
UPDATE public.courses SET dist_yellow = 5759, par = 72 WHERE lower(name) = lower('Blue Green Golf de Villeray') AND lower(coalesce(city, '')) = lower('Saint-Pierre-du-Perray');
UPDATE public.courses SET dist_yellow = 5859, par = 71 WHERE lower(name) = lower('Exclusiv Golf de Coudray - Les Marronniers') AND lower(coalesce(city, '')) = lower('Le Coudray-Montceaux');
UPDATE public.courses SET dist_yellow = 5748, holes = 18, par = 71 WHERE lower(name) = lower('Golf de Mennecy Chevannes - 18T') AND lower(coalesce(city, '')) = lower('Chevannes');
UPDATE public.courses SET dist_yellow = 5074, par = 70 WHERE lower(name) = lower('Golf de Saint-Germain-lès-Corbeil') AND lower(coalesce(city, '')) = lower('Saint-Germain-lès-Corbeil');
UPDATE public.courses SET dist_yellow = 2630, par = 58 WHERE lower(name) = lower('Exclusiv Golf de Coudray - La Guiche') AND lower(coalesce(city, '')) = lower('Le Coudray-Montceaux');
UPDATE public.courses SET dist_yellow = 4926, holes = 9, par = 66 WHERE lower(name) = lower('Golf de Gif-Chevry') AND lower(coalesce(city, '')) = lower('Gif-sur-Yvette');
UPDATE public.courses SET dist_yellow = 1282, par = 54 WHERE lower(name) = lower('Golf de Sénart - L''Arbalète') AND lower(coalesce(city, '')) = lower('Saint-Pierre-du-Perray');
UPDATE public.courses SET par = 67 WHERE lower(name) = lower('Golf de Saint-Cloud - Parcours Jaune') AND lower(coalesce(city, '')) = lower('Garches');
UPDATE public.courses SET dist_yellow = 3830, par = 64 WHERE lower(name) = lower('Golf du Stade Français Haras Lupin') AND lower(coalesce(city, '')) = lower('Vaucresson');
UPDATE public.courses SET dist_yellow = 4856, par = 70 WHERE lower(name) = lower('Paris Golf & Country Club - 9T') AND lower(coalesce(city, '')) = lower('Saint-Cloud');
UPDATE public.courses SET dist_yellow = 1764, par = 56 WHERE lower(name) = lower('Golf départemental de la Poudrerie') AND lower(coalesce(city, '')) = lower('Sevran');
UPDATE public.courses SET par = 72 WHERE lower(name) = lower('Golf d''Ormesson') AND lower(coalesce(city, '')) = lower('Ormesson-sur-Marne');
UPDATE public.courses SET dist_yellow = 5113, par = 71 WHERE lower(name) = lower('Garden Golf Cergy-Pontoise') AND lower(coalesce(city, '')) = lower('Vauréal');
UPDATE public.courses SET dist_yellow = 5158, par = 72 WHERE lower(name) = lower('Golf de Maudétour-en-Vexin') AND lower(coalesce(city, '')) = lower('Maudétour-en-Vexin');
UPDATE public.courses SET par = 71 WHERE lower(name) = lower('Golf de Seraincourt') AND lower(coalesce(city, '')) = lower('Seraincourt');
UPDATE public.courses SET dist_yellow = 5129, par = 72 WHERE lower(name) = lower('Golf de Villarceaux - Grand Parcours') AND lower(coalesce(city, '')) = lower('Chaussy');
UPDATE public.courses SET par = 71 WHERE lower(name) = lower('Golf de l''Isle-Adam') AND lower(coalesce(city, '')) = lower('L''Isle-Adam');

-- Crécy Golf - Vignoly  →  Crécy Golf - Parcours Vignoly (Crécy-la-Chapelle)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 4, NULL, 379),
    (2, 5, NULL, 469),
    (3, 3, NULL, 139),
    (4, 4, NULL, 301),
    (5, 4, NULL, 369),
    (6, 5, NULL, 447),
    (7, 4, NULL, 328),
    (8, 3, NULL, 156),
    (9, 4, NULL, 309),
    (10, 4, NULL, 468),
    (11, 3, NULL, 130),
    (12, 4, NULL, 327),
    (13, 5, NULL, 452),
    (14, 4, NULL, 287),
    (15, 4, NULL, 274),
    (16, 3, NULL, 125),
    (17, 4, NULL, 379),
    (18, 4, NULL, 385)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Crécy Golf - Parcours Vignoly')
 AND lower(coalesce(c.city, '')) = lower('Crécy-la-Chapelle')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Exclusiv Golf du Château de Cél  →  Exclusiv Golf du Château de Cély (Cély-en-Bière)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 5, 10, 409),
    (2, 4, 16, 287),
    (3, 4, 6, 305),
    (4, 4, 14, 301),
    (5, 3, 4, 146),
    (6, 5, 2, 498),
    (7, 3, 18, 123),
    (8, 4, 8, 284),
    (9, 4, 12, 286),
    (10, 5, 5, 414),
    (11, 4, 13, 307),
    (12, 3, 3, 141),
    (13, 4, 7, 300),
    (14, 4, 15, 313),
    (15, 5, 1, 551),
    (16, 4, 11, 304),
    (17, 3, 17, 133),
    (18, 4, 9, 329)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Exclusiv Golf du Château de Cély')
 AND lower(coalesce(c.city, '')) = lower('Cély-en-Bière')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf Clément Ader  →  Golf Clément Ader (Gretz-Armainvilliers)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 5, 9, 462),
    (2, 3, 17, 138),
    (3, 4, 1, 340),
    (4, 4, 15, 324),
    (5, 4, 13, 323),
    (6, 3, 11, 151),
    (7, 5, 5, 475),
    (8, 4, 7, 345),
    (9, 4, 3, 302),
    (10, 4, 12, 301),
    (11, 4, 14, 333),
    (12, 4, 4, 326),
    (13, 5, 6, 476),
    (14, 3, 18, 154),
    (15, 4, 8, 333),
    (16, 5, 10, 440),
    (17, 3, 16, 168),
    (18, 4, 2, 358)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf Clément Ader')
 AND lower(coalesce(c.city, '')) = lower('Gretz-Armainvilliers')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf Paris Val dEurope (Disneyl  →  Golf Paris Val d'Europe (Disneyland) (Magny-le-Hongre)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 5, 8, 435),
    (2, 3, 16, 145),
    (3, 5, 4, 420),
    (4, 4, 12, 310),
    (5, 3, 18, 110),
    (6, 5, 2, 450),
    (7, 4, 6, 330),
    (8, 3, 14, 155),
    (9, 4, 10, 305),
    (10, 4, 13, 315),
    (11, 4, 17, 270),
    (12, 4, 5, 387),
    (13, 3, 9, 191),
    (14, 5, 1, 507),
    (15, 3, 15, 153),
    (16, 4, 11, 291),
    (17, 4, 3, 361),
    (18, 5, 7, 458)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf Paris Val d''Europe (Disneyland)')
 AND lower(coalesce(c.city, '')) = lower('Magny-le-Hongre')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf dOzoir-la-Ferrière  →  Golf d'Ozoir-la-Ferrière (Ozoir-la-Ferrière)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 5, 15, 442),
    (2, 3, 13, 146),
    (3, 4, 3, 322),
    (4, 4, 7, 320),
    (5, 3, 11, 166),
    (6, 4, 9, 329),
    (7, 4, 5, 341),
    (8, 5, 17, 407),
    (9, 4, 1, 401),
    (10, 3, 6, 137),
    (11, 5, 16, 436),
    (12, 4, 10, 320),
    (13, 4, 4, 337),
    (14, 4, 18, 268),
    (15, 3, 12, 174),
    (16, 4, 2, 342),
    (17, 4, 14, 311),
    (18, 5, 8, 433)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf d''Ozoir-la-Ferrière')
 AND lower(coalesce(c.city, '')) = lower('Ozoir-la-Ferrière')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf de Bois-le-Roi (9T)  →  Golf de Bois-le-Roi (Bois-le-Roi)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 4, 15, 251),
    (2, 3, 9, 152),
    (3, 4, 5, 244),
    (4, 3, 11, 149),
    (5, 3, 17, 181),
    (6, 4, 3, 260),
    (7, 5, 7, 441),
    (8, 5, 1, 451),
    (9, 3, 13, 184)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf de Bois-le-Roi')
 AND lower(coalesce(c.city, '')) = lower('Bois-le-Roi')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf de Bussy-Guermantes - La G  →  Golf de Bussy-Guermantes - La Gondoire (Bussy-Saint-Georges)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 5, 3, 455),
    (2, 3, 5, 134),
    (3, 4, 1, 373),
    (4, 4, 13, 305),
    (5, 4, 11, 319),
    (6, 5, 9, 456),
    (7, 3, 15, 149),
    (8, 4, 7, 318),
    (9, 4, 17, 291)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf de Bussy-Guermantes - La Gondoire')
 AND lower(coalesce(c.city, '')) = lower('Bussy-Saint-Georges')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf de Bussy-Guermantes - La J  →  Golf de Bussy-Guermantes - La Brèche (Bussy-Saint-Georges)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 4, 2, 384),
    (2, 3, 4, 170),
    (3, 4, 10, 290),
    (4, 5, 6, 458),
    (5, 4, 8, 296),
    (6, 4, 18, 284),
    (7, 3, 14, 124),
    (8, 5, 16, 444),
    (9, 4, 12, 356),
    (10, 5, 15, 442),
    (11, 3, 13, 144),
    (12, 4, 3, 324),
    (13, 4, 1, 374),
    (14, 4, 17, 258),
    (15, 4, 11, 265),
    (16, 4, 7, 312),
    (17, 3, 9, 155),
    (18, 5, 5, 449)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf de Bussy-Guermantes - La Brèche')
 AND lower(coalesce(c.city, '')) = lower('Bussy-Saint-Georges')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf de Fontainebleau  →  Golf de Fontainebleau (Fontainebleau)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 4, 17, 295),
    (2, 3, 5, 158),
    (3, 5, 15, 470),
    (4, 4, 1, 365),
    (5, 4, 11, 305),
    (6, 4, 3, 376),
    (7, 3, 9, 157),
    (8, 5, 7, 501),
    (9, 4, 13, 286),
    (10, 3, 12, 151),
    (11, 5, 6, 483),
    (12, 5, 16, 389),
    (13, 4, 8, 335),
    (14, 3, 14, 137),
    (15, 4, 4, 350),
    (16, 4, 2, 336),
    (17, 4, 18, 229),
    (18, 4, 10, 344)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf de Fontainebleau')
 AND lower(coalesce(c.city, '')) = lower('Fontainebleau')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf de Meaux-Boutigny  →  Golf de Meaux-Boutigny (Boutigny)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 4, 16, 305),
    (2, 3, 8, 172),
    (3, 4, 6, 297),
    (4, 4, 10, 321),
    (5, 5, 12, 478),
    (6, 4, 15, 352),
    (7, 5, 4, 440),
    (8, 3, 14, 105),
    (9, 4, 2, 412),
    (10, 3, 11, 162),
    (11, 4, 17, 305),
    (12, 4, 3, 401),
    (13, 4, 5, 321),
    (14, 3, 13, 155),
    (15, 4, 18, 275),
    (16, 5, 1, 433),
    (17, 3, 9, 151),
    (18, 5, 7, 462)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf de Meaux-Boutigny')
 AND lower(coalesce(c.city, '')) = lower('Boutigny')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf de Montereau la Forteresse  →  Golf de Montereau la Forteresse (Thoury-Férottes)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 4, 16, 292),
    (2, 5, 4, 447),
    (3, 3, 14, 133),
    (4, 5, 2, 446),
    (5, 3, 8, 160),
    (6, 4, 6, 298),
    (7, 4, 12, 310),
    (8, 5, 10, 401),
    (9, 4, 18, 250),
    (10, 4, 5, 363),
    (11, 4, 1, 371),
    (12, 5, 15, 412),
    (13, 4, 17, 306),
    (14, 3, 9, 184),
    (15, 4, 11, 306),
    (16, 3, 3, 150),
    (17, 4, 13, 337),
    (18, 4, 7, 376)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf de Montereau la Forteresse')
 AND lower(coalesce(c.city, '')) = lower('Thoury-Férottes')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf de Réveillon (Lésigny 18T)  →  Golf de Réveillon - Parcours 18T (Lésigny)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 4, 16, 234),
    (2, 5, 4, 457),
    (3, 3, 12, 144),
    (4, 4, 10, 313),
    (5, 4, 2, 385),
    (6, 4, 6, 350),
    (7, 4, 14, 297),
    (8, 4, 8, 321),
    (9, 3, 18, 122),
    (10, 4, 11, 280),
    (11, 5, 5, 480),
    (12, 3, 9, 160),
    (13, 4, 7, 334),
    (14, 5, 3, 489),
    (15, 3, 15, 164),
    (16, 4, 1, 371),
    (17, 4, 13, 302),
    (18, 4, 17, 266)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf de Réveillon - Parcours 18T')
 AND lower(coalesce(c.city, '')) = lower('Lésigny')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf AS La Croix des Anges (9T)  →  Golf de La Croix des Anges (Réau)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 4, NULL, 254),
    (2, 3, NULL, 214),
    (3, 3, NULL, 179),
    (4, 4, NULL, 262),
    (5, 4, NULL, 294),
    (6, 4, NULL, 297),
    (7, 3, NULL, 168),
    (8, 3, NULL, 172),
    (9, 3, NULL, 177)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf de La Croix des Anges')
 AND lower(coalesce(c.city, '')) = lower('Réau')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf de la Marsaudière (9T)  →  Golf de la Marsaudière (Chevry-Cossigny)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 3, 15, 121),
    (2, 4, 7, 312),
    (3, 4, 13, 256),
    (4, 4, 3, 337),
    (5, 3, 17, 108),
    (6, 5, 5, 467),
    (7, 4, 9, 326),
    (8, 4, 11, 235),
    (9, 4, 1, 319)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf de la Marsaudière')
 AND lower(coalesce(c.city, '')) = lower('Chevry-Cossigny')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf de Torcy (9T)  →  Golf de Torcy (Torcy)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 4, 11, 282),
    (2, 5, 5, 487),
    (3, 3, 7, 159),
    (4, 4, 9, 298),
    (5, 5, 15, 390),
    (6, 4, 3, 342),
    (7, 4, 17, 283),
    (8, 3, 13, 119),
    (9, 4, 1, 328)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf de Torcy')
 AND lower(coalesce(c.city, '')) = lower('Torcy')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Béthemont Golf & Country Club (  →  Béthemont Golf & Country Club (Poissy)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 4, 7, 324),
    (2, 3, 13, 137),
    (3, 4, 1, 356),
    (4, 4, 3, 317),
    (5, 3, 15, 119),
    (6, 5, 9, 461),
    (7, 3, 17, 131),
    (8, 5, 11, 443),
    (9, 5, 5, 419),
    (10, 4, 14, 300),
    (11, 5, 8, 455),
    (12, 4, 6, 290),
    (13, 3, 12, 144),
    (14, 5, 16, 471),
    (15, 4, 2, 337),
    (16, 4, 10, 380),
    (17, 3, 18, 140),
    (18, 4, 4, 320)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Béthemont Golf & Country Club')
 AND lower(coalesce(c.city, '')) = lower('Poissy')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Exclusiv Golf de Rochefort  →  Exclusiv Golf de Rochefort (Rochefort-en-Yvelines)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 4, 9, 346),
    (2, 5, 11, 457),
    (3, 3, 17, 121),
    (4, 4, 3, 327),
    (5, 5, 15, 405),
    (6, 4, 13, 300),
    (7, 4, 5, 327),
    (8, 3, 7, 177),
    (9, 4, 1, 369),
    (10, 3, 8, 150),
    (11, 5, 18, 430),
    (12, 3, 14, 134),
    (13, 4, 2, 347),
    (14, 5, 10, 433),
    (15, 4, 16, 298),
    (16, 4, 4, 333),
    (17, 3, 12, 142),
    (18, 4, 6, 315)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Exclusiv Golf de Rochefort')
 AND lower(coalesce(c.city, '')) = lower('Rochefort-en-Yvelines')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf Blue Green Guerville  →  Golf Blue Green de Guerville (Guerville)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 4, 11, 325),
    (2, 4, 1, 368),
    (3, 3, 17, 112),
    (4, 5, 7, 407),
    (5, 4, 13, 290),
    (6, 5, 3, 458),
    (7, 4, 5, 287),
    (8, 3, 15, 127),
    (9, 5, 9, 406),
    (10, 5, 10, 406),
    (11, 4, 18, 294),
    (12, 3, 16, 150),
    (13, 4, 8, 348),
    (14, 3, 14, 153),
    (15, 4, 2, 364),
    (16, 5, 6, 459),
    (17, 3, 12, 170),
    (18, 4, 4, 359)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf Blue Green de Guerville')
 AND lower(coalesce(c.city, '')) = lower('Guerville')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf Blue Green Villennes  →  Golf Blue Green de Villennes (Villennes-sur-Seine)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 4, 17, 285),
    (2, 4, 9, 252),
    (3, 3, 15, 134),
    (4, 5, 11, 472),
    (5, 4, 1, 353),
    (6, 3, 13, 111),
    (7, 4, 3, 315),
    (8, 4, 7, 344),
    (9, 4, 5, 305),
    (10, 3, 14, 137),
    (11, 4, 18, 265),
    (12, 4, 12, 307),
    (13, 4, 10, 258),
    (14, 4, 6, 329),
    (15, 3, 4, 147),
    (16, 4, 16, 278),
    (17, 5, 2, 434),
    (18, 4, 8, 308)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf Blue Green de Villennes')
 AND lower(coalesce(c.city, '')) = lower('Villennes-sur-Seine')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf Isabella (Plaisir)  →  Golf Isabella (Plaisir)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 4, 6, 335),
    (2, 4, 12, 336),
    (3, 5, 2, 461),
    (4, 3, 18, 122),
    (5, 4, 10, 289),
    (6, 4, 14, 267),
    (7, 5, 4, 410),
    (8, 3, 16, 128),
    (9, 4, 8, 254),
    (10, 5, 11, 422),
    (11, 4, 1, 361),
    (12, 4, 5, 336),
    (13, 4, 3, 365),
    (14, 3, 9, 129),
    (15, 4, 15, 270),
    (16, 4, 17, 280),
    (17, 3, 13, 141),
    (18, 4, 7, 345)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf Isabella')
 AND lower(coalesce(c.city, '')) = lower('Plaisir')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf National - Aigle  →  Golf National - L'Aigle (Guyancourt)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 4, 12, 310),
    (2, 4, 2, 369),
    (3, 4, 18, 248),
    (4, 3, 16, 147),
    (5, 4, 6, 377),
    (6, 3, 14, 165),
    (7, 5, 10, 480),
    (8, 4, 8, 348),
    (9, 4, 4, 327),
    (10, 3, 9, 186),
    (11, 4, 11, 348),
    (12, 4, 1, 324),
    (13, 3, 17, 153),
    (14, 4, 5, 366),
    (15, 5, 15, 431),
    (16, 4, 3, 323),
    (17, 5, 13, 454),
    (18, 4, 7, 320)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf National - L''Aigle')
 AND lower(coalesce(c.city, '')) = lower('Guyancourt')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf National - Albatros  →  Golf National - L'Albatros (Guyancourt)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 4, NULL, 318),
    (2, 3, NULL, 141),
    (3, 5, NULL, 456),
    (4, 4, NULL, 385),
    (5, 4, NULL, 339),
    (6, 4, NULL, 295),
    (7, 4, NULL, 411),
    (8, 3, NULL, 169),
    (9, 5, NULL, 499),
    (10, 4, NULL, 298),
    (11, 3, NULL, 132),
    (12, 4, NULL, 337),
    (13, 4, NULL, 339),
    (14, 5, NULL, 437),
    (15, 4, NULL, 345),
    (16, 3, NULL, 137),
    (17, 4, NULL, 405),
    (18, 5, NULL, 411)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf National - L''Albatros')
 AND lower(coalesce(c.city, '')) = lower('Guyancourt')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf National - Oiselet  →  Golf National - L'Oiselet (Guyancourt)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 3, NULL, 136),
    (2, 4, NULL, 250),
    (3, 4, NULL, 256),
    (4, 3, NULL, 207),
    (5, 4, NULL, 264),
    (6, 3, NULL, 105),
    (7, 3, NULL, 149),
    (8, 3, NULL, 136),
    (9, 4, NULL, 250)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf National - L''Oiselet')
 AND lower(coalesce(c.city, '')) = lower('Guyancourt')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf de Feucherolles  →  Exclusiv Golf de Feucherolles (Feucherolles)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 4, 18, 325),
    (2, 4, 12, 346),
    (3, 4, 16, 298),
    (4, 3, 10, 176),
    (5, 4, 14, 308),
    (6, 5, 8, 435),
    (7, 3, 6, 153),
    (8, 4, 4, 384),
    (9, 5, 2, 497),
    (10, 4, 11, 333),
    (11, 5, 7, 453),
    (12, 4, 9, 353),
    (13, 3, 3, 198),
    (14, 4, 1, 371),
    (15, 3, 5, 155),
    (16, 4, 17, 301),
    (17, 4, 15, 321),
    (18, 5, 13, 470)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Exclusiv Golf de Feucherolles')
 AND lower(coalesce(c.city, '')) = lower('Feucherolles')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf de Fourqueux - BlancBleu  →  Golf Country Club de Fourqueux - Blanc/Bleu (Fourqueux)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 4, 5, 331),
    (2, 4, 7, 304),
    (3, 3, 13, 139),
    (4, 4, 11, 279),
    (5, 5, 9, 478),
    (6, 4, 1, 352),
    (7, 5, 15, 470),
    (8, 3, 17, 125),
    (9, 5, 3, 455),
    (10, 4, 8, 284),
    (11, 5, 16, 418),
    (12, 4, 10, 270),
    (13, 4, 2, 369),
    (14, 4, 12, 286),
    (15, 3, 4, 156),
    (16, 5, 18, 430),
    (17, 4, 14, 252),
    (18, 3, 6, 152)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf Country Club de Fourqueux - Blanc/Bleu')
 AND lower(coalesce(c.city, '')) = lower('Fourqueux')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf de Joyenval - Marly  →  Golf de Joyenval - Marly (Chambourcy)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 4, 17, 297),
    (2, 5, 9, 456),
    (3, 3, 15, 123),
    (4, 5, 5, 451),
    (5, 4, 13, 286),
    (6, 4, 1, 341),
    (7, 4, 11, 318),
    (8, 3, 7, 140),
    (9, 4, 3, 331),
    (10, 4, 2, 306),
    (11, 3, 14, 167),
    (12, 4, 8, 245),
    (13, 4, 4, 372),
    (14, 4, 18, 325),
    (15, 4, 12, 342),
    (16, 5, 10, 439),
    (17, 3, 6, 168),
    (18, 5, 16, 428)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf de Joyenval - Marly')
 AND lower(coalesce(c.city, '')) = lower('Chambourcy')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf de Joyenval - Retz  →  Golf de Joyenval - Retz (Chambourcy)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 4, 15, 326),
    (2, 3, 9, 134),
    (3, 4, 17, 304),
    (4, 5, 1, 435),
    (5, 4, 3, 291),
    (6, 5, 11, 455),
    (7, 3, 13, 148),
    (8, 4, 5, 349),
    (9, 4, 7, 344),
    (10, 4, 8, 369),
    (11, 3, 2, 122),
    (12, 4, 18, 244),
    (13, 5, 14, 452),
    (14, 4, 4, 371),
    (15, 3, 12, 128),
    (16, 5, 10, 447),
    (17, 4, 6, 294),
    (18, 4, 16, 336)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf de Joyenval - Retz')
 AND lower(coalesce(c.city, '')) = lower('Chambourcy')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf de Maisons-Laffitte  →  Golf de Maisons-Laffitte (Maisons-Laffitte)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 3, 17, 100),
    (2, 4, 3, 327),
    (3, 4, 9, 269),
    (4, 3, 13, 106),
    (5, 4, 5, 246),
    (6, 3, 11, 120),
    (7, 3, 15, 95),
    (8, 3, 1, 134),
    (9, 3, 7, 140)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf de Maisons-Laffitte')
 AND lower(coalesce(c.city, '')) = lower('Maisons-Laffitte')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf de Saint-Germain - Le Gran  →  Golf de Saint-Germain - Le Grand Parcours (Saint-Germain-en-Laye)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 4, 3, 381),
    (2, 5, 15, 438),
    (3, 4, 11, 318),
    (4, 4, 1, 405),
    (5, 3, 7, 164),
    (6, 5, 9, 504),
    (7, 3, 5, 139),
    (8, 4, 13, 313),
    (9, 5, 17, 430),
    (10, 4, 10, 285),
    (11, 3, 12, 129),
    (12, 4, 4, 362),
    (13, 4, 14, 302),
    (14, 4, 2, 358),
    (15, 5, 16, 468),
    (16, 4, 18, 277),
    (17, 3, 8, 141),
    (18, 4, 6, 379)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf de Saint-Germain - Le Grand Parcours')
 AND lower(coalesce(c.city, '')) = lower('Saint-Germain-en-Laye')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf de Saint-Marc (Jouy-en-Jos  →  Golf de Saint-Marc (Jouy-en-Josas)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 4, 16, 268),
    (2, 4, 10, 339),
    (3, 5, 2, 500),
    (4, 4, 6, 364),
    (5, 4, 12, 271),
    (6, 3, 14, 135),
    (7, 4, 4, 315),
    (8, 5, 18, 435),
    (9, 3, 8, 181),
    (10, 4, 5, 379),
    (11, 4, 11, 298),
    (12, 3, 7, 140),
    (13, 5, 3, 472),
    (14, 4, 1, 327),
    (15, 3, 15, 142),
    (16, 5, 13, 435),
    (17, 3, 9, 167),
    (18, 4, 17, 291)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf de Saint-Marc')
 AND lower(coalesce(c.city, '')) = lower('Jouy-en-Josas')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf de Saint-Nom-la-Bretêche -  →  Golf de Saint-Nom-la-Bretêche - Bleu (Saint-Nom-la-Bretêche)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 4, 3, 393),
    (2, 4, 11, 307),
    (3, 3, 7, 168),
    (4, 4, 1, 390),
    (5, 4, 13, 314),
    (6, 5, 15, 437),
    (7, 3, 9, 127),
    (8, 4, 5, 352),
    (9, 4, 17, 304),
    (10, 5, 18, 425),
    (11, 3, 10, 143),
    (12, 4, 4, 357),
    (13, 5, 14, 433),
    (14, 4, 16, 285),
    (15, 4, 2, 376),
    (16, 5, 8, 483),
    (17, 3, 12, 141),
    (18, 4, 6, 341)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf de Saint-Nom-la-Bretêche - Bleu')
 AND lower(coalesce(c.city, '')) = lower('Saint-Nom-la-Bretêche')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf de Saint-Nom-la-Bretêche 2  →  Golf de Saint-Nom-la-Bretêche - Rouge (Saint-Nom-la-Bretêche)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 4, 15, 321),
    (2, 4, 11, 364),
    (3, 3, 9, 139),
    (4, 4, 3, 350),
    (5, 5, 17, 429),
    (6, 4, 1, 373),
    (7, 5, 13, 457),
    (8, 4, 5, 377),
    (9, 3, 7, 149),
    (10, 4, 4, 365),
    (11, 4, 18, 324),
    (12, 5, 14, 452),
    (13, 3, 6, 177),
    (14, 4, 10, 315),
    (15, 4, 2, 346),
    (16, 3, 8, 151),
    (17, 5, 16, 427),
    (18, 4, 12, 320)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf de Saint-Nom-la-Bretêche - Rouge')
 AND lower(coalesce(c.city, '')) = lower('Saint-Nom-la-Bretêche')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf de Saint-Quentin-en-Yvelin  →  Golf de Saint-Quentin-en-Yvelines - Bleu (Trappes)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 4, 4, 360),
    (2, 3, 14, 172),
    (3, 4, 10, 347),
    (4, 4, 2, 372),
    (5, 3, 16, 150),
    (6, 4, 18, 284),
    (7, 5, 12, 443),
    (8, 5, 8, 489),
    (9, 4, 6, 343),
    (10, 3, 15, 140),
    (11, 4, 13, 288),
    (12, 5, 1, 451),
    (13, 5, 5, 458),
    (14, 3, 11, 132),
    (15, 4, 3, 350),
    (16, 4, 7, 358),
    (17, 4, 17, 294),
    (18, 4, 9, 310)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf de Saint-Quentin-en-Yvelines - Bleu')
 AND lower(coalesce(c.city, '')) = lower('Trappes')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf de Saint-Quentin-en-Yvel 2  →  Golf de Saint-Quentin-en-Yvelines - Rouge (Trappes)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 5, 12, 425),
    (2, 4, 4, 322),
    (3, 3, 18, 139),
    (4, 5, 14, 426),
    (5, 4, 2, 354),
    (6, 4, 10, 267),
    (7, 3, 8, 174),
    (8, 4, 6, 330),
    (9, 4, 16, 304),
    (10, 3, 15, 130),
    (11, 4, 13, 310),
    (12, 4, 3, 291),
    (13, 4, 1, 347),
    (14, 5, 7, 467),
    (15, 4, 5, 330),
    (16, 3, 17, 145),
    (17, 4, 9, 272),
    (18, 5, 11, 423)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf de Saint-Quentin-en-Yvelines - Rouge')
 AND lower(coalesce(c.city, '')) = lower('Trappes')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf de Villacoublay  →  Golf de Villacoublay (Région Aérienne) (Vélizy-Villacoublay)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 4, 6, 303),
    (2, 5, 18, 432),
    (3, 4, 2, 420),
    (4, 5, 8, 463),
    (5, 3, 12, 128),
    (6, 4, 10, 334),
    (7, 3, 16, 144),
    (8, 5, 14, 437),
    (9, 3, 4, 164),
    (10, 4, 7, 360),
    (11, 4, 3, 356),
    (12, 4, 9, 341),
    (13, 4, 1, 323),
    (14, 5, 13, 443),
    (15, 3, 11, 165),
    (16, 5, 5, 452),
    (17, 3, 17, 144),
    (18, 4, 15, 310)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf de Villacoublay (Région Aérienne)')
 AND lower(coalesce(c.city, '')) = lower('Vélizy-Villacoublay')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf de la Boulie - La Forêt  →  Golf de la Boulie - La Forêt (Versailles)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 4, NULL, 360),
    (2, 3, NULL, 117),
    (3, 5, NULL, 434),
    (4, 4, NULL, 403),
    (5, 5, NULL, 412),
    (6, 4, NULL, 326),
    (7, 4, NULL, 383),
    (8, 4, NULL, 326),
    (9, 3, NULL, 159),
    (10, 5, NULL, 509),
    (11, 3, NULL, 158),
    (12, 4, NULL, 365),
    (13, 3, NULL, 134),
    (14, 5, NULL, 459),
    (15, 4, NULL, 370),
    (16, 4, NULL, 358),
    (17, 4, NULL, 302),
    (18, 4, NULL, 326)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf de la Boulie - La Forêt')
 AND lower(coalesce(c.city, '')) = lower('Versailles')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf des Boucles de Seine  →  Golf des Boucles de Seine (Moisson)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 4, 6, 304),
    (2, 4, 7, 295),
    (3, 4, 3, 375),
    (4, 3, 15, 145),
    (5, 5, 1, 407),
    (6, 4, 5, 328),
    (7, 3, 18, 107),
    (8, 4, 9, 300),
    (9, 4, 4, 358),
    (10, 4, 8, 334),
    (11, 4, 13, 276),
    (12, 4, 11, 297),
    (13, 4, 12, 314),
    (14, 4, 10, 272),
    (15, 3, 16, 158),
    (16, 4, 14, 278),
    (17, 3, 17, 127),
    (18, 5, 2, 441)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf des Boucles de Seine')
 AND lower(coalesce(c.city, '')) = lower('Moisson')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf des Yvelines (La Queue-lez  →  Golf des Yvelines (La Queue-lez-Yvelines)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 4, 17, 334),
    (2, 4, 9, 317),
    (3, 4, 5, 359),
    (4, 3, 11, 150),
    (5, 4, 1, 332),
    (6, 5, 15, 453),
    (7, 4, 13, 307),
    (8, 5, 3, 489),
    (9, 3, 7, 162),
    (10, 4, 14, 336),
    (11, 3, 10, 130),
    (12, 4, 2, 374),
    (13, 5, 16, 417),
    (14, 3, 8, 166),
    (15, 4, 6, 356),
    (16, 4, 18, 293),
    (17, 4, 4, 352),
    (18, 5, 12, 476)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf des Yvelines')
 AND lower(coalesce(c.city, '')) = lower('La Queue-lez-Yvelines')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf du Château de la Chouette  →  Golf du Château de la Chouette (Gaillon-sur-Montcient)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 4, NULL, 375),
    (2, 4, NULL, 343),
    (3, 3, NULL, 141),
    (4, 5, NULL, 430),
    (5, 4, NULL, 308),
    (6, 4, NULL, 360),
    (7, 3, NULL, 113),
    (8, 5, NULL, 432),
    (9, 4, NULL, 343),
    (10, 4, NULL, 295),
    (11, 5, NULL, 463),
    (12, 4, NULL, 338),
    (13, 4, NULL, 376),
    (14, 3, NULL, 141),
    (15, 4, NULL, 321),
    (16, 4, NULL, 318),
    (17, 3, NULL, 153),
    (18, 5, NULL, 421)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf du Château de la Chouette')
 AND lower(coalesce(c.city, '')) = lower('Gaillon-sur-Montcient')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf du Prieuré - Est  →  Golf du Prieuré - Est (Sailly)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 4, 16, 294),
    (2, 4, 2, 318),
    (3, 3, 12, 170),
    (4, 5, 10, 411),
    (5, 4, 6, 311),
    (6, 3, 18, 149),
    (7, 4, 14, 283),
    (8, 4, 8, 369),
    (9, 4, 4, 327),
    (10, 5, 1, 492),
    (11, 4, 11, 328),
    (12, 3, 9, 176),
    (13, 5, 5, 426),
    (14, 4, 15, 273),
    (15, 4, 3, 325),
    (16, 4, 13, 320),
    (17, 5, 7, 458),
    (18, 3, 17, 137)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf du Prieuré - Est')
 AND lower(coalesce(c.city, '')) = lower('Sailly')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf du Prieuré - Ouest  →  Golf du Prieuré - Ouest (Sailly)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 3, 17, 161),
    (2, 4, 3, 358),
    (3, 4, 11, 364),
    (4, 4, 5, 364),
    (5, 5, 1, 452),
    (6, 3, 9, 174),
    (7, 4, 7, 362),
    (8, 5, 13, 447),
    (9, 3, 15, 151),
    (10, 5, 8, 433),
    (11, 3, 16, 144),
    (12, 4, 2, 353),
    (13, 3, 18, 140),
    (14, 4, 14, 258),
    (15, 5, 10, 397),
    (16, 4, 4, 351),
    (17, 4, 6, 334),
    (18, 5, 12, 438)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf du Prieuré - Ouest')
 AND lower(coalesce(c.city, '')) = lower('Sailly')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- La Vaucouleurs - La Rivière  →  La Vaucouleurs - La Rivière (Civry-la-Forêt)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 4, 15, 292),
    (2, 5, 7, 465),
    (3, 3, 11, 195),
    (4, 4, 5, 295),
    (5, 5, 9, 455),
    (6, 4, 3, 342),
    (7, 3, 17, 147),
    (8, 5, 13, 424),
    (9, 4, 1, 333),
    (10, 5, 16, 452),
    (11, 3, 18, 117),
    (12, 4, 4, 338),
    (13, 3, 8, 132),
    (14, 3, 12, 146),
    (15, 4, 2, 315),
    (16, 5, 6, 468),
    (17, 5, 14, 434),
    (18, 4, 10, 289)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('La Vaucouleurs - La Rivière')
 AND lower(coalesce(c.city, '')) = lower('Civry-la-Forêt')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- La Vaucouleurs - Les Vallons  →  La Vaucouleurs - Les Vallons (Civry-la-Forêt)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 4, 15, 278),
    (2, 3, 13, 147),
    (3, 5, 5, 465),
    (4, 3, 11, 144),
    (5, 4, 1, 373),
    (6, 4, 9, 246),
    (7, 3, 17, 105),
    (8, 4, 7, 264),
    (9, 5, 3, 467),
    (10, 5, 12, 459),
    (11, 4, 18, 277),
    (12, 3, 14, 149),
    (13, 4, 10, 293),
    (14, 4, 6, 314),
    (15, 3, 16, 142),
    (16, 5, 4, 433),
    (17, 4, 2, 380),
    (18, 3, 8, 168)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('La Vaucouleurs - Les Vallons')
 AND lower(coalesce(c.city, '')) = lower('Civry-la-Forêt')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Daily Golf de Buc (9T)  →  Golf de Buc-Toussus (Dailybuc) (Buc)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 3, 7, 125),
    (2, 3, 11, 105),
    (3, 3, 5, 130),
    (4, 4, 1, 265),
    (5, 3, 13, 100),
    (6, 3, 9, 130),
    (7, 3, 17, 100),
    (8, 3, 15, 110),
    (9, 3, 3, 100)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf de Buc-Toussus (Dailybuc)')
 AND lower(coalesce(c.city, '')) = lower('Buc')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Tremblay-Mauldre Château Bertin  →  Golf du Tremblay-sur-Mauldre - Château (Le Tremblay-sur-Mauldre)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 4, 9, 321),
    (2, 5, 5, 436),
    (3, 3, 8, 122),
    (4, 4, 6, 262),
    (5, 4, 7, 303),
    (6, 4, 1, 365),
    (7, 3, 2, 162),
    (8, 4, 4, 304),
    (9, 5, 3, 450)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf du Tremblay-sur-Mauldre - Château')
 AND lower(coalesce(c.city, '')) = lower('Le Tremblay-sur-Mauldre')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Tremblay-Mauldre Parc Irlandais  →  Golf du Tremblay-sur-Mauldre - Le Parc (Le Tremblay-sur-Mauldre)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 3, 8, 58),
    (2, 3, 1, 90),
    (3, 3, 7, 44),
    (4, 3, 2, 79),
    (5, 3, 3, 74),
    (6, 3, 5, 63),
    (7, 3, 4, 60),
    (8, 3, 6, 54),
    (9, 3, 9, 34)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf du Tremblay-sur-Mauldre - Le Parc')
 AND lower(coalesce(c.city, '')) = lower('Le Tremblay-sur-Mauldre')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf de l'Île Fleurie (9T)  →  Île Fleurie Golf Club (Chatou)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 3, 5, 155),
    (2, 3, 13, 165),
    (3, 3, 15, 161),
    (4, 3, 9, 155),
    (5, 4, 1, 228),
    (6, 3, 11, 154),
    (7, 3, 17, 99),
    (8, 3, 3, 183),
    (9, 3, 7, 146)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Île Fleurie Golf Club')
 AND lower(coalesce(c.city, '')) = lower('Chatou')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf de la Boulie - La Vallée  →  Golf de la Boulie - La Vallée (Versailles)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 4, 5, 349),
    (2, 4, 1, 390),
    (3, 3, 9, 143),
    (4, 5, 17, 445),
    (5, 4, 3, 382),
    (6, 4, 11, 309),
    (7, 3, 7, 157),
    (8, 5, 13, 454),
    (9, 4, 15, 274),
    (10, 3, 6, 171),
    (11, 5, 14, 447),
    (12, 4, 12, 299),
    (13, 3, 4, 149),
    (14, 4, 8, 362),
    (15, 3, 10, 156),
    (16, 4, 2, 371),
    (17, 5, 16, 433),
    (18, 5, 18, 379)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf de la Boulie - La Vallée')
 AND lower(coalesce(c.city, '')) = lower('Versailles')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Blue Green Golf de Villeray  →  Blue Green Golf de Villeray (Saint-Pierre-du-Perray)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 3, 16, 130),
    (2, 4, 12, 315),
    (3, 4, 4, 318),
    (4, 5, 10, 476),
    (5, 4, 2, 379),
    (6, 4, 6, 341),
    (7, 3, 14, 162),
    (8, 4, 8, 342),
    (9, 5, 18, 445),
    (10, 4, 7, 324),
    (11, 4, 1, 334),
    (12, 4, 5, 359),
    (13, 4, 11, 318),
    (14, 3, 9, 149),
    (15, 5, 15, 428),
    (16, 3, 13, 171),
    (17, 4, 3, 341),
    (18, 5, 17, 427)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Blue Green Golf de Villeray')
 AND lower(coalesce(c.city, '')) = lower('Saint-Pierre-du-Perray')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Exclusiv Golf de Coudray - Les   →  Exclusiv Golf de Coudray - Les Marronniers (Le Coudray-Montceaux)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 4, 7, 379),
    (2, 4, 5, 349),
    (3, 3, 15, 131),
    (4, 5, 11, 474),
    (5, 4, 1, 412),
    (6, 4, 17, 300),
    (7, 4, 9, 332),
    (8, 5, 3, 483),
    (9, 3, 13, 172),
    (10, 4, 18, 291),
    (11, 4, 14, 325),
    (12, 5, 8, 496),
    (13, 4, 12, 313),
    (14, 3, 10, 168),
    (15, 4, 6, 318),
    (16, 4, 2, 399),
    (17, 3, 16, 168),
    (18, 4, 4, 349)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Exclusiv Golf de Coudray - Les Marronniers')
 AND lower(coalesce(c.city, '')) = lower('Le Coudray-Montceaux')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf dEtiolles - Les Cerfs  →  Golf d'Etiolles - Les Cerfs (Etiolles)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 5, 8, 443),
    (2, 4, 12, 336),
    (3, 4, 2, 372),
    (4, 4, 18, 236),
    (5, 3, 10, 155),
    (6, 5, 4, 468),
    (7, 4, 14, 322),
    (8, 5, 6, 442),
    (9, 3, 16, 134),
    (10, 4, 13, 285),
    (11, 4, 7, 330),
    (12, 4, 1, 365),
    (13, 5, 3, 457),
    (14, 4, 17, 266),
    (15, 3, 15, 137),
    (16, 5, 9, 431),
    (17, 3, 11, 184),
    (18, 4, 5, 342)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf d''Etiolles - Les Cerfs')
 AND lower(coalesce(c.city, '')) = lower('Etiolles')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf de Courson Stade Français   →  Golf de Courson Stade Français - Lilas/Orange (Courson-Monteloup)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 4, 8, 330),
    (2, 4, 16, 315),
    (3, 4, 2, 352),
    (4, 3, 14, 158),
    (5, 4, 6, 333),
    (6, 5, 10, 464),
    (7, 4, 4, 390),
    (8, 3, 12, 116),
    (9, 5, 18, 446),
    (10, 5, 17, 439),
    (11, 4, 9, 309),
    (12, 4, 11, 337),
    (13, 4, 15, 318),
    (14, 3, 5, 136),
    (15, 4, 3, 374),
    (16, 4, 1, 342),
    (17, 3, 13, 152),
    (18, 5, 7, 442)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf de Courson Stade Français - Lilas/Orange')
 AND lower(coalesce(c.city, '')) = lower('Courson-Monteloup')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf de Courson Stade Françai 2  →  Golf de Courson Stade Français - Vert/Noir (Courson-Monteloup)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 4, 7, 391),
    (2, 3, 17, 142),
    (3, 4, 15, 361),
    (4, 4, 9, 372),
    (5, 5, 1, 502),
    (6, 4, 3, 396),
    (7, 4, 5, 367),
    (8, 3, 13, 148),
    (9, 5, 11, 500),
    (10, 4, 2, 365),
    (11, 3, 18, 139),
    (12, 4, 10, 345),
    (13, 4, 12, 351),
    (14, 5, 4, 435),
    (15, 3, 14, 114),
    (16, 4, 8, 335),
    (17, 4, 6, 312),
    (18, 5, 16, 461)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf de Courson Stade Français - Vert/Noir')
 AND lower(coalesce(c.city, '')) = lower('Courson-Monteloup')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf de Forges-les-Bains  →  Golf de Forges-les-Bains (Forges-les-Bains)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 4, 2, 352),
    (2, 3, 14, 160),
    (3, 4, 8, 337),
    (4, 4, 12, 265),
    (5, 5, 16, 447),
    (6, 4, 10, 376),
    (7, 4, 6, 332),
    (8, 3, 4, 198),
    (9, 5, 18, 459),
    (10, 4, 1, 361),
    (11, 4, 3, 358),
    (12, 3, 9, 147),
    (13, 5, 13, 435),
    (14, 4, 11, 329),
    (15, 3, 7, 143),
    (16, 4, 17, 312),
    (17, 4, 5, 317),
    (18, 5, 15, 475)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf de Forges-les-Bains')
 AND lower(coalesce(c.city, '')) = lower('Forges-les-Bains')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf de Marivaux (Janvry)  →  Golf de Marivaux (Janvry)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 4, 3, 317),
    (2, 4, 7, 286),
    (3, 3, 13, 124),
    (4, 5, 5, 445),
    (5, 4, 1, 282),
    (6, 4, 11, 322),
    (7, 5, 17, 425),
    (8, 3, 15, 163),
    (9, 4, 9, 328),
    (10, 4, 2, 347),
    (11, 3, 16, 133),
    (12, 4, 8, 337),
    (13, 5, 6, 443),
    (14, 4, 12, 305),
    (15, 4, 10, 353),
    (16, 5, 18, 434),
    (17, 3, 14, 147),
    (18, 4, 4, 354)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf de Marivaux')
 AND lower(coalesce(c.city, '')) = lower('Janvry')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf de Mennecy Chevannes (18T)  →  Golf de Mennecy Chevannes - 18T (Chevannes)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 4, NULL, 363),
    (2, 4, NULL, 375),
    (3, 4, NULL, 364),
    (4, 3, NULL, 120),
    (5, 4, NULL, 332),
    (6, 5, NULL, 461),
    (7, 4, NULL, 316),
    (8, 3, NULL, 142),
    (9, 4, NULL, 328),
    (10, 4, NULL, 333),
    (11, 4, NULL, 343),
    (12, 5, NULL, 484),
    (13, 3, NULL, 153),
    (14, 4, NULL, 324),
    (15, 4, NULL, 311),
    (16, 5, NULL, 470),
    (17, 3, NULL, 150),
    (18, 4, NULL, 379)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf de Mennecy Chevannes - 18T')
 AND lower(coalesce(c.city, '')) = lower('Chevannes')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf de Saint-Aubin - Le Mesnil  →  Golf de Saint-Aubin - Le Mesnil (Saint-Aubin)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 5, NULL, 467),
    (2, 4, NULL, 265),
    (3, 4, NULL, 299),
    (4, 4, NULL, 334),
    (5, 3, NULL, 131),
    (6, 4, NULL, 265),
    (7, 4, NULL, 300),
    (8, 4, NULL, 360),
    (9, 4, NULL, 308),
    (10, 3, NULL, 143),
    (11, 4, NULL, 308),
    (12, 4, NULL, 316),
    (13, 4, NULL, 280),
    (14, 5, NULL, 424),
    (15, 3, NULL, 152),
    (16, 4, NULL, 309),
    (17, 3, NULL, 140),
    (18, 4, NULL, 309)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf de Saint-Aubin - Le Mesnil')
 AND lower(coalesce(c.city, '')) = lower('Saint-Aubin')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf de Saint-Germain-lès-Corbe  →  Golf de Saint-Germain-lès-Corbeil (Saint-Germain-lès-Corbeil)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 4, NULL, 264),
    (2, 4, NULL, 325),
    (3, 5, NULL, 436),
    (4, 5, NULL, 405),
    (5, 3, NULL, 140),
    (6, 5, NULL, 509),
    (7, 3, NULL, 158),
    (8, 3, NULL, 157),
    (9, 4, NULL, 277),
    (10, 3, NULL, 128),
    (11, 5, NULL, 410),
    (12, 4, NULL, 272),
    (13, 3, NULL, 156),
    (14, 4, NULL, 283),
    (15, 4, NULL, 358),
    (16, 3, NULL, 164),
    (17, 4, NULL, 344),
    (18, 4, NULL, 288)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf de Saint-Germain-lès-Corbeil')
 AND lower(coalesce(c.city, '')) = lower('Saint-Germain-lès-Corbeil')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf de Sénart - Les Cygnes  →  Golf de Sénart - Les Cygnes (Saint-Pierre-du-Perray)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 4, 5, 365),
    (2, 5, 13, 459),
    (3, 3, 7, 173),
    (4, 4, 11, 349),
    (5, 4, 1, 388),
    (6, 3, 9, 131),
    (7, 5, 15, 484),
    (8, 3, 17, 121),
    (9, 4, 3, 364),
    (10, 4, 6, 374),
    (11, 4, 14, 308),
    (12, 3, 12, 122),
    (13, 5, 4, 490),
    (14, 4, 8, 339),
    (15, 4, 10, 351),
    (16, 3, 16, 145),
    (17, 5, 18, 416),
    (18, 4, 2, 353)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf de Sénart - Les Cygnes')
 AND lower(coalesce(c.city, '')) = lower('Saint-Pierre-du-Perray')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf de Val Grand (Bondoufle)  →  Golf de Val Grand (Bondoufle)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 5, 8, 443),
    (2, 4, 10, 336),
    (3, 4, 14, 287),
    (4, 4, 6, 354),
    (5, 3, 12, 117),
    (6, 4, 18, 263),
    (7, 5, 4, 421),
    (8, 3, 16, 155),
    (9, 4, 2, 354),
    (10, 3, 9, 168),
    (11, 5, 1, 463),
    (12, 4, 13, 296),
    (13, 3, 7, 158),
    (14, 5, 5, 409),
    (15, 4, 17, 281),
    (16, 4, 15, 303),
    (17, 3, 11, 148),
    (18, 4, 3, 343)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf de Val Grand')
 AND lower(coalesce(c.city, '')) = lower('Bondoufle')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- DailyGolf Verrières (9T)  →  Golf de Verrières-le-Buisson (Verrières-le-Buisson)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 4, 3, 240),
    (2, 3, 1, 145),
    (3, 3, 5, 132),
    (4, 3, 4, 125),
    (5, 3, 6, 95),
    (6, 3, 2, 145),
    (7, 3, 8, 80),
    (8, 3, 7, 103),
    (9, 3, 9, 75)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf de Verrières-le-Buisson')
 AND lower(coalesce(c.city, '')) = lower('Verrières-le-Buisson')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Coudray - La Guiche (9T)  →  Exclusiv Golf de Coudray - La Guiche (Le Coudray-Montceaux)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 3, 5, 103),
    (2, 3, 7, 82),
    (3, 3, 2, 150),
    (4, 4, 9, 215),
    (5, 3, 1, 176),
    (6, 4, 3, 264),
    (7, 3, 8, 82),
    (8, 3, 6, 99),
    (9, 3, 4, 144)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Exclusiv Golf de Coudray - La Guiche')
 AND lower(coalesce(c.city, '')) = lower('Le Coudray-Montceaux')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Gif-Chevry - Chevry II (9T)  →  Golf de Gif-Chevry (Gif-sur-Yvette)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 4, 15, 296),
    (2, 4, 11, 328),
    (3, 3, 7, 170),
    (4, 4, 1, 411),
    (5, 3, 13, 148),
    (6, 4, 3, 363),
    (7, 4, 5, 311),
    (8, 3, 17, 155),
    (9, 4, 9, 281)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf de Gif-Chevry')
 AND lower(coalesce(c.city, '')) = lower('Gif-sur-Yvette')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Greenparc P&P L'Arbalète (9T)  →  Golf de Sénart - L'Arbalète (Saint-Pierre-du-Perray)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 3, 7, 75),
    (2, 3, 3, 67),
    (3, 3, 6, 73),
    (4, 3, 9, 74),
    (5, 3, 8, 78),
    (6, 3, 2, 85),
    (7, 3, 1, 51),
    (8, 3, 4, 64),
    (9, 3, 5, 74)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf de Sénart - L''Arbalète')
 AND lower(coalesce(c.city, '')) = lower('Saint-Pierre-du-Perray')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Morangis La Galande (9T)  →  Golf de Morangis La Galande (Morangis)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, 'blanc'
FROM (VALUES
    (1, 3, 9, 81),
    (2, 3, 6, 89),
    (3, 3, 5, 71),
    (4, 3, 3, 100),
    (5, 3, 8, 115),
    (6, 3, 2, 154),
    (7, 3, 4, 105),
    (8, 3, 1, 149),
    (9, 3, 7, 110)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf de Morangis La Galande')
 AND lower(coalesce(c.city, '')) = lower('Morangis')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf de Rueil-Malmaison  →  Golf de Rueil-Malmaison (Rueil-Malmaison)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 3, 15, 119),
    (2, 4, 5, 185),
    (3, 5, 1, 366),
    (4, 4, 3, 251),
    (5, 4, 11, 212),
    (6, 3, 17, 108),
    (7, 3, 7, 141),
    (8, 3, 13, 92),
    (9, 3, 9, 110)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf de Rueil-Malmaison')
 AND lower(coalesce(c.city, '')) = lower('Rueil-Malmaison')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf de Saint-Cloud - Parcours   →  Golf de Saint-Cloud - Parcours Jaune (Garches)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 4, 3, 325),
    (2, 3, 9, 135),
    (3, 5, 7, 400),
    (4, 3, 13, 140),
    (5, 4, 5, 294),
    (6, 3, 17, 105),
    (7, 4, 1, 302),
    (8, 4, 11, 290),
    (9, 5, 15, 372),
    (10, 3, 14, 130),
    (11, 5, 12, 383),
    (12, 4, 4, 355),
    (13, 3, 16, 145),
    (14, 3, 10, 129),
    (15, 4, 6, 277),
    (16, 3, 18, 120),
    (17, 4, 2, 271),
    (18, 3, 8, 150)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf de Saint-Cloud - Parcours Jaune')
 AND lower(coalesce(c.city, '')) = lower('Garches')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf de Saint-Cloud - Parcour 2  →  Golf de Saint-Cloud - Parcours Vert (Garches)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 4, 5, 353),
    (2, 4, 7, 331),
    (3, 5, 17, 400),
    (4, 4, 11, 273),
    (5, 4, 9, 310),
    (6, 3, 15, 129),
    (7, 4, 1, 330),
    (8, 3, 13, 120),
    (9, 4, 3, 340),
    (10, 4, 2, 360),
    (11, 3, 10, 134),
    (12, 4, 6, 303),
    (13, 3, 8, 146),
    (14, 4, 14, 254),
    (15, 5, 16, 420),
    (16, 4, 18, 242),
    (17, 5, 12, 428),
    (18, 4, 4, 339)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf de Saint-Cloud - Parcours Vert')
 AND lower(coalesce(c.city, '')) = lower('Garches')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf du Haras de Jardy (Vaucres  →  Golf du Haras de Jardy (Vaucresson)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 3, 6, 112),
    (2, 3, 5, 90),
    (3, 4, 1, 330),
    (4, 3, 3, 115),
    (5, 3, 7, 106),
    (6, 3, 9, 84),
    (7, 4, 2, 258),
    (8, 3, 8, 100),
    (9, 4, 4, 293)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf du Haras de Jardy')
 AND lower(coalesce(c.city, '')) = lower('Vaucresson')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf du Stade Français Haras Lu  →  Golf du Stade Français Haras Lupin (Vaucresson)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 3, 9, 97),
    (2, 4, 6, 338),
    (3, 3, 5, 134),
    (4, 4, 7, 294),
    (5, 4, 1, 268),
    (6, 3, 8, 122),
    (7, 3, 3, 116),
    (8, 4, 4, 243),
    (9, 4, 2, 303)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf du Stade Français Haras Lupin')
 AND lower(coalesce(c.city, '')) = lower('Vaucresson')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Paris Golf & Country Club (Sain  →  Paris Golf & Country Club - 9T (Saint-Cloud)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 4, 9, 324),
    (2, 3, 3, 163),
    (3, 4, 11, 240),
    (4, 4, 5, 278),
    (5, 5, 1, 472),
    (6, 3, 13, 137),
    (7, 4, 15, 250),
    (8, 4, 17, 223),
    (9, 4, 7, 341)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Paris Golf & Country Club - 9T')
 AND lower(coalesce(c.city, '')) = lower('Saint-Cloud')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf de Rosny-sous-Bois  →  Golf de Rosny-sous-Bois (Rosny-sous-Bois)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 5, 7, 384),
    (2, 3, 17, 105),
    (3, 4, 11, 249),
    (4, 4, 5, 222),
    (5, 4, 9, 188),
    (6, 3, 1, 163),
    (7, 3, 13, 123),
    (8, 3, 3, 114),
    (9, 4, 15, 176)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf de Rosny-sous-Bois')
 AND lower(coalesce(c.city, '')) = lower('Rosny-sous-Bois')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf départemental de la Poudre  →  Golf départemental de la Poudrerie (Sevran)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 3, 15, 87),
    (2, 3, 17, 70),
    (3, 3, 5, 98),
    (4, 3, 13, 77),
    (5, 3, 7, 108),
    (6, 3, 1, 74),
    (7, 3, 11, 83),
    (8, 3, 9, 64),
    (9, 4, 3, 221)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf départemental de la Poudrerie')
 AND lower(coalesce(c.city, '')) = lower('Sevran')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf dOrmesson  →  Golf d'Ormesson (Ormesson-sur-Marne)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 5, 9, 360),
    (2, 4, 3, 340),
    (3, 4, 13, 270),
    (4, 4, 1, 320),
    (5, 3, 15, 125),
    (6, 4, 7, 320),
    (7, 4, 17, 260),
    (8, 5, 5, 411),
    (9, 3, 11, 155),
    (10, 4, 2, 345),
    (11, 3, 12, 170),
    (12, 5, 10, 395),
    (13, 4, 6, 326),
    (14, 3, 16, 140),
    (15, 4, 4, 310),
    (16, 5, 8, 390),
    (17, 4, 18, 210),
    (18, 4, 14, 326)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf d''Ormesson')
 AND lower(coalesce(c.city, '')) = lower('Ormesson-sur-Marne')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf du Parc du Tremblay (Champ  →  Golf du Parc du Tremblay (Champigny-sur-Marne)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 3, 3, 146),
    (2, 3, 9, 79),
    (3, 3, 15, 57),
    (4, 3, 13, 52),
    (5, 3, 17, 62),
    (6, 3, 7, 126),
    (7, 3, 5, 132),
    (8, 3, 11, 72),
    (9, 3, 1, 202)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf du Parc du Tremblay')
 AND lower(coalesce(c.city, '')) = lower('Champigny-sur-Marne')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Garden Golf Cergy-Pontoise (Vau  →  Garden Golf Cergy-Pontoise (Vauréal)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 4, 17, 226),
    (2, 3, 16, 112),
    (3, 4, 1, 410),
    (4, 3, 12, 125),
    (5, 4, 3, 316),
    (6, 3, 13, 139),
    (7, 4, 2, 429),
    (8, 4, 14, 277),
    (9, 5, 10, 408),
    (10, 4, 6, 321),
    (11, 5, 5, 431),
    (12, 3, 15, 107),
    (13, 4, 7, 272),
    (14, 4, 4, 319),
    (15, 4, 18, 230),
    (16, 5, 9, 411),
    (17, 3, 11, 157),
    (18, 5, 8, 423)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Garden Golf Cergy-Pontoise')
 AND lower(coalesce(c.city, '')) = lower('Vauréal')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Garden Golf Gadancourt  →  Garden Golf Gadancourt (Gadancourt)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 4, 3, 324),
    (2, 4, 11, 300),
    (3, 4, 13, 288),
    (4, 3, 9, 111),
    (5, 4, 8, 330),
    (6, 5, 1, 408),
    (7, 4, 5, 291),
    (8, 4, 18, 290),
    (9, 3, 10, 148),
    (10, 5, 14, 399),
    (11, 3, 16, 135),
    (12, 4, 6, 298),
    (13, 5, 7, 413),
    (14, 4, 2, 342),
    (15, 3, 12, 116),
    (16, 4, 15, 288),
    (17, 5, 17, 383),
    (18, 4, 4, 329)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Garden Golf Gadancourt')
 AND lower(coalesce(c.city, '')) = lower('Gadancourt')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf Blue Green Bellefontaine -  →  Golf Blue Green Bellefontaine - Le Plessis 9 (Bellefontaine)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 4, 15, 252),
    (2, 4, 9, 296),
    (3, 5, 11, 365),
    (4, 3, 17, 110),
    (5, 4, 7, 316),
    (6, 3, 5, 139),
    (7, 4, 3, 287),
    (8, 4, 1, 320),
    (9, 5, 13, 420)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf Blue Green Bellefontaine - Le Plessis 9')
 AND lower(coalesce(c.city, '')) = lower('Bellefontaine')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf Club dAbleiges - Les Étang  →  Golf Club d'Ableiges - Les Étangs (Ableiges)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 4, 4, 347),
    (2, 4, 6, 301),
    (3, 5, 12, 444),
    (4, 3, 8, 152),
    (5, 4, 2, 340),
    (6, 5, 10, 421),
    (7, 4, 16, 244),
    (8, 3, 18, 109),
    (9, 4, 14, 271),
    (10, 5, 13, 403),
    (11, 4, 3, 336),
    (12, 3, 11, 123),
    (13, 4, 5, 313),
    (14, 4, 7, 252),
    (15, 5, 15, 412),
    (16, 4, 1, 270),
    (17, 3, 17, 130),
    (18, 4, 9, 319)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf Club d''Ableiges - Les Étangs')
 AND lower(coalesce(c.city, '')) = lower('Ableiges')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf Hôtel Mont Griffon - Les L  →  Golf Hôtel de Mont Griffon - Les Lacs (Luzarches)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 4, 16, 294),
    (2, 4, 6, 299),
    (3, 4, 4, 281),
    (4, 4, 12, 315),
    (5, 5, 10, 436),
    (6, 3, 18, 142),
    (7, 3, 14, 118),
    (8, 5, 8, 419),
    (9, 4, 2, 316),
    (10, 4, 17, 304),
    (11, 3, 13, 115),
    (12, 5, 9, 436),
    (13, 5, 3, 422),
    (14, 4, 15, 270),
    (15, 4, 1, 334),
    (16, 3, 11, 127),
    (17, 4, 7, 321),
    (18, 4, 5, 275)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf Hôtel de Mont Griffon - Les Lacs')
 AND lower(coalesce(c.city, '')) = lower('Luzarches')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf International de Roissy  →  Golf International de Roissy (Roissy-en-France)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, 'noir'
FROM (VALUES
    (1, 4, 16, 339),
    (2, 5, 9, 505),
    (3, 3, 10, 207),
    (4, 5, 8, 510),
    (5, 4, 2, 413),
    (6, 4, 6, 395),
    (7, 3, 15, 176),
    (8, 4, 12, 346),
    (9, 4, 7, 348),
    (10, 5, 13, 502),
    (11, 4, 14, 318),
    (12, 4, 1, 434),
    (13, 3, 11, 198),
    (14, 4, 17, 353),
    (15, 4, 5, 382),
    (16, 3, 18, 150),
    (17, 4, 4, 390),
    (18, 5, 3, 533)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf International de Roissy')
 AND lower(coalesce(c.city, '')) = lower('Roissy-en-France')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf de Gonesse  →  Golf de Gonesse (Gonesse)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 4, 7, 308),
    (2, 4, 5, 310),
    (3, 3, 15, 104),
    (4, 5, 3, 439),
    (5, 4, 11, 251),
    (6, 4, 1, 344),
    (7, 4, 9, 287),
    (8, 3, 13, 111),
    (9, 5, 17, 390)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf de Gonesse')
 AND lower(coalesce(c.city, '')) = lower('Gonesse')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf de Maudétour-en-Vexin  →  Golf de Maudétour-en-Vexin (Maudétour-en-Vexin)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 4, 2, 365),
    (2, 4, 8, 317),
    (3, 3, 16, 134),
    (4, 5, 6, 408),
    (5, 4, 12, 285),
    (6, 4, 10, 281),
    (7, 4, 14, 135),
    (8, 4, 4, 308),
    (9, 4, 18, 329),
    (10, 4, 5, 281),
    (11, 4, 13, 287),
    (12, 4, 3, 375),
    (13, 4, 17, 168),
    (14, 4, 9, 324),
    (15, 3, 11, 164),
    (16, 4, 1, 411),
    (17, 4, 15, 256),
    (18, 5, 7, 330)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf de Maudétour-en-Vexin')
 AND lower(coalesce(c.city, '')) = lower('Maudétour-en-Vexin')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf de Montmorency - Les Châta  →  Golf de Montmorency - Les Châtaigniers (Domont)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 4, 15, 295),
    (2, 3, 5, 155),
    (3, 4, 3, 336),
    (4, 4, 11, 251),
    (5, 5, 7, 408),
    (6, 4, 17, 305),
    (7, 5, 13, 422),
    (8, 3, 9, 162),
    (9, 4, 1, 347),
    (10, 4, 14, 292),
    (11, 4, 8, 253),
    (12, 3, 12, 142),
    (13, 5, 2, 407),
    (14, 3, 18, 115),
    (15, 4, 4, 293),
    (16, 3, 16, 136),
    (17, 5, 6, 398),
    (18, 4, 10, 272)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf de Montmorency - Les Châtaigniers')
 AND lower(coalesce(c.city, '')) = lower('Domont')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf de Saint-Ouen-lAumône  →  Golf de Saint-Ouen-l'Aumône (Saint-Ouen-l'Aumône)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 3, 5, 75),
    (2, 3, 3, 102),
    (3, 3, 11, 75),
    (4, 3, 17, 53),
    (5, 3, 15, 75),
    (6, 3, 1, 75),
    (7, 3, 13, 85),
    (8, 3, 7, 69),
    (9, 3, 9, 66)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf de Saint-Ouen-l''Aumône')
 AND lower(coalesce(c.city, '')) = lower('Saint-Ouen-l''Aumône')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf de Seraincourt  →  Golf de Seraincourt (Seraincourt)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 4, 3, 257),
    (2, 3, 15, 116),
    (3, 4, 7, 258),
    (4, 3, 1, 121),
    (5, 4, 9, 303),
    (6, 4, 5, 274),
    (7, 5, 17, 417),
    (8, 3, 11, 104),
    (9, 5, 13, 410),
    (10, 4, 12, 302),
    (11, 4, 4, 355),
    (12, 3, 18, 93),
    (13, 4, 16, 310),
    (14, 4, 6, 326),
    (15, 5, 14, 410),
    (16, 4, 8, 333),
    (17, 3, 2, 156),
    (18, 5, 10, 388)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf de Seraincourt')
 AND lower(coalesce(c.city, '')) = lower('Seraincourt')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf de Villarceaux - Grand Par  →  Golf de Villarceaux - Grand Parcours (Chaussy)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 4, 7, 294),
    (2, 4, 3, 361),
    (3, 3, 9, 134),
    (4, 5, 11, 401),
    (5, 4, 13, 283),
    (6, 5, 17, 398),
    (7, 4, 5, 313),
    (8, 4, 1, 362),
    (9, 3, 15, 134),
    (10, 5, 4, 436),
    (11, 3, 8, 108),
    (12, 5, 2, 379),
    (13, 4, 16, 283),
    (14, 4, 12, 305),
    (15, 4, 14, 240),
    (16, 4, 10, 286),
    (17, 3, 18, 101),
    (18, 4, 6, 311)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf de Villarceaux - Grand Parcours')
 AND lower(coalesce(c.city, '')) = lower('Chaussy')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Golf de lIsle-Adam  →  Golf de l'Isle-Adam (L'Isle-Adam)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 4, NULL, 300),
    (2, 4, NULL, 317),
    (3, 4, NULL, 261),
    (4, 3, NULL, 139),
    (5, 5, NULL, 429),
    (6, 3, NULL, 101),
    (7, 4, NULL, 242),
    (8, 4, NULL, 395),
    (9, 4, NULL, 338),
    (10, 4, NULL, 271),
    (11, 4, NULL, 273),
    (12, 5, NULL, 427),
    (13, 3, NULL, 144),
    (14, 4, NULL, 343),
    (15, 4, NULL, 271),
    (16, 3, NULL, 114),
    (17, 4, NULL, 317),
    (18, 5, NULL, 470)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf de l''Isle-Adam')
 AND lower(coalesce(c.city, '')) = lower('L''Isle-Adam')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Paris International Golf Club (  →  Paris International Golf Club (Baillet-en-France)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, 'blanc'
FROM (VALUES
    (1, 4, 15, 338),
    (2, 3, 17, 140),
    (3, 5, 9, 499),
    (4, 4, 5, 358),
    (5, 4, 1, 379),
    (6, 3, 11, 161),
    (7, 4, 7, 331),
    (8, 5, 13, 468),
    (9, 4, 3, 369),
    (10, 5, 14, 443),
    (11, 4, 2, 328),
    (12, 4, 6, 384),
    (13, 3, 18, 131),
    (14, 4, 12, 295),
    (15, 3, 10, 171),
    (16, 4, 8, 369),
    (17, 4, 4, 359),
    (18, 5, 16, 462)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Paris International Golf Club')
 AND lower(coalesce(c.city, '')) = lower('Baillet-en-France')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Mont Griffon - L'Arbalétrier  →  Golf Hôtel de Mont Griffon - L'Arbalétrier (Luzarches)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 3, 4, 105),
    (2, 3, 7, 88),
    (3, 3, 6, 120),
    (4, 3, 5, 86),
    (5, 3, 9, 105),
    (6, 3, 2, 102),
    (7, 3, 8, 80),
    (8, 3, 3, 85),
    (9, 3, 1, 115)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf Hôtel de Mont Griffon - L''Arbalétrier')
 AND lower(coalesce(c.city, '')) = lower('Luzarches')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Mont Griffon - La Forêt (9T)  →  Golf Hôtel de Mont Griffon - La Forêt (Luzarches)
INSERT INTO public.course_holes (course_id, hole_number, par, hcp_index, dist_yellow_m, tee_note)
SELECT c.id, v.hole_number, v.par, v.hcp_index, v.dist_m, NULL
FROM (VALUES
    (1, 5, 1, 382),
    (2, 3, 17, 131),
    (3, 4, 5, 386),
    (4, 4, 11, 317),
    (5, 5, 3, 430),
    (6, 3, 7, 170),
    (7, 4, 15, 322),
    (8, 4, 13, 315),
    (9, 3, 9, 112)
) AS v(hole_number, par, hcp_index, dist_m)
JOIN public.courses c
  ON lower(c.name) = lower('Golf Hôtel de Mont Griffon - La Forêt')
 AND lower(coalesce(c.city, '')) = lower('Luzarches')
ON CONFLICT (course_id, hole_number) DO UPDATE
  SET par = EXCLUDED.par,
      hcp_index = EXCLUDED.hcp_index,
      dist_yellow_m = EXCLUDED.dist_yellow_m,
      tee_note = EXCLUDED.tee_note;

-- Verification (run manually):
--   SELECT count(DISTINCT course_id) AS courses,
--          count(*) AS holes
--   FROM public.course_holes;
--   -- every seeded course's hole-par sum must equal courses.par:
--   SELECT c.name, c.par, sum(ch.par) AS par_sum
--   FROM public.course_holes ch JOIN public.courses c ON c.id = ch.course_id
--   GROUP BY c.id HAVING sum(ch.par) IS DISTINCT FROM c.par;
